### ISSUE TITLE
Authentication Flows not executed after Identity Provider Redirect

### ISSUE THREAD

**Issue by cgeorgilakis** [keycloak/keycloak#10250]
### Describe the bug

We have configured an authedication flow as shown here :
![authedicate_otp](https://user-images.githubusercontent.com/55974447/154234809-3e9398c3-8455-4362-b2da-a68e4f1926d6.PNG)
We want for some clients users use compulsorily OTP ( as in screenshot). For other clients we want to deny access based on User role. Our users are mainly from external Identity Providers.
The problem is that any action ( otp, deny access) in Authedication flow  after Identity Provider Redirect is not executed for external Users. For Keycloak Users everything is ok.

We want to mention that configure Identity Provider "Post Login Flow" is not acceptable for our case. Client MUST decide about the authedication flow NOT the Identity Provider.

Identity Provider Redirect must return in already executed authedication flow after "First Login Flow" and "Post Login Flow" have finished.

### Version

16.1.0

### Expected behavior

Users from external Identity Providers use compulsorily OTP for some clients and Keycloak must be able to deny access to these users in other clients.

### Actual behavior

Users from external Identity Providers do not ask for OTP and Keycloak can not deny access to these users in other clients.

### How to Reproduce?

1. Configure authedication flow as in screenshot.
2. Make account console use this authedication flow(browser - otp) as browser flow
3. Configure in this realm an external Identity Provider
4. Try to login in realm Account Console from external Identity Provider

After all this user will not ask to use OTP.

**Comment by bs-matil** [comment]
May #10120 can solve this in the future

**Comment by cgeorgilakis** [comment]
Although step-authedication ([#10120](https://github.com/keycloak/keycloak/discussions/10120)) is an important feature added in Keycloak, it did not solve this bug. Not all client authorization is related with acr.

However, I will test with step-authedication and users from external Identity Providers.

**Comment by cgeorgilakis** [comment]
I have corrected the jira issue. This problem is happen after Identity Provider User log in. After Identity Provider User log in - using Username Password Form, Client browser authedication flow is not proceed with following steps as it does with Keycloak User log in.

**Comment by doombubbles** [comment]
Encountered this issue myself (version 16.1.1). All steps of the authentication flow after the Identity Provider login within the Username Password form are completely ignored. This unfortunately makes authentication flows unusable for what we're trying to accomplish.

**Comment by GVincenzo** [comment]
Issue still exists on Keycloak's version 19.0.1.
Is there a work around for this bug? we use mainly external IDP for authentication flow and we would like to check role and the number of sessions before end login process

**Comment by sschu** [comment]
@GVincenzo That's what IDP post-login flows are for.

**Comment by cgeorgilakis** [comment]
IDP post-login flows is inappropriate for most of the cases. Unless you have only one client browser flow! See my comments in [related github discussion](https://github.com/keycloak/keycloak/discussions/13743#discussioncomment-3447482).

**Comment by sschu** [comment]
@cgeorgilakis But the use case @GVincenzo had (number of sessions/roles of user) it does not depend on the client so a post-login flow could be used to solve the problem.

**Comment by GVincenzo** [comment]
@sschu we have a number of different clients with specific authentication flow where each client has a specific role.
Such for example:
Application 1: Generic User portal
Application 2: Management Application with role 1
Application 3: Administration portal with role 2

The desire is to deny access on keycloak layer to avoid access to the application .
While the IDP is the same for all the applications, the app 1 is free, app 2 e app3 need different specific roles.

What I havae done is define a base Auth Flow with a login step (2 alternative IDP od Cookies) and conditional step with role check.
As the image below:

![authFlowEx](https://user-images.githubusercontent.com/72270995/185973416-37bcc4c5-f72d-476a-afde-ce613302e5b7.PNG)

let me know if there is a different or a better way to do that (I'm quite new to keycloak)

**Comment by sschu** [comment]
@GVincenzo Have you checked the scopes-setting of clients? You can actually give a user a role but only allow specific clients to act on behalf of the user with that role (i.e. the client won't get the role in the token, even if the user has it). To do that, you have to go to the client settings, the scope tab and disable "Full Scope Allowed" and instead pick the roles a client might get.

**Comment by GVincenzo** [comment]
@sschu yes, I did it
![clientScope](https://user-images.githubusercontent.com/72270995/186098863-416aac51-4f8c-4326-9712-f3076ece0875.PNG)
and the token has all the info as expected.
My concern about the auth flow, is the role check in login step and in case of IDP it's not performed

**Comment by sschu** [comment]
The thing is, if the client does not have a permission, its your application's job to say "You don't have access." Why would you want to abort an authentication flow in that case?

**Comment by GVincenzo** [comment]
The desired effect is to not allow the user to reach the application but to block him during login.
And as far as I understand, this should be a Keycloak feature.
Infact if I already have a cookie it works as expected while if I do a login using the IDP Redidirector, it doesn't.

**Comment by cgeorgilakis** [comment]
For cookie ( also for Keycloak users), it works because authentication flow does not use IDP Redirector.
The problem exists for IDP Redidirector and login via external IdP ( login form).
That's why it is important Keycloak team reviews and helps to finish [the realted PR](https://github.com/keycloak/keycloak/pull/12891).

**Comment by sebbrousse** [comment]
I run into this issue as well. I was looking to implement [flow as described in the documentation](https://www.keycloak.org/docs/latest/server_admin/#explicitly-deny-allow-access-in-conditional-flows) for a particular client but it is useless with an IdP.

**Comment by 4meepo** [comment]
Same issue here.

**Comment by trixpan** [comment]
@pedroigor @mposolda we can confirm this bug still exists in KC 21.x as well.

**Comment by cgeorgilakis** [comment]
> @pedroigor @mposolda we can confirm this bug still exists in KC 21.x as well.

@pedroigor @mposolda could you help finish [the PR](https://github.com/keycloak/keycloak/pull/12891) and correct test failures?
This is an important bug in Keycloak and as you see still exists.

**Comment by pedroigor** [comment]
Looks like we have an inconsistency when users are already logged in and when they are authenticating through a broker. I agree that we should expect the client authentication flow to be running just like when the user is already authenticated.

However, I'm not sure if we can assume that federated users should always go through the client (browser) flow set to a client. You might not want to force OTP the first time when the user is created to a realm. It is a different use case and perhaps why we have been working like that?

@mposolda Wdyt?

**Comment by cgeorgilakis** [comment]
> Looks like we have an inconsistency when users are already logged in and when they are authenticating through a broker. I agree that we should expect the client authentication flow to be running just like when the user is already authenticated.
> 
> However, I'm not sure if we can assume that federated users should always go through the client (browser) flow set to a client. You might not want to force OTP when the user is created to a realm. It is a different use case and perhaps why we have been working like that?
> 
> @mposolda Wdyt?

The most important is that now you can not configure important Client authentication flows like `Deny Access`, `acr` for broker users. OTP for us is less important. Broker users are more and more used especially with Social Identity Providers.

For the case mentioned, configure OTP only for Keycloak users can be configured in registration flow .Moreover, administrator can add `Conditional executions`. Maybe we can add extra execution.

**Comment by vitorcont** [comment]
Any Updates on this Issue / PR? This is really major, even in 22.0 we are having difficulties with this

**Comment by vitorcont** [comment]
For anyone who needs it, I managed to come up with a workaround by adding a custom Javascript Provider as a authorization script that runs as a post login flow on my IDP

On this example I am validating, 3 different clients, **client-1**, **client-2** and **client-3** , each one of these clients has a client role **(role-1, role-2, role-3)** used to determine if a user has access to a client. This script pulls the user session, verifies which client he is loging into and validates the needed role.

To add the custom script just follow the instructions at the [documentation](https://www.keycloak.org/docs/latest/server_development/#_script_providers)

my-auth-script.js
```
AuthenticationFlowError = Java.type("org.keycloak.authentication.AuthenticationFlowError");

function authenticate(context) {
  var currentClient = String(authenticationSession.getClient().getClientId());
  switch (currentClient) {
    case "client-1":
      var role = authenticationSession.getClient().getRole("role-1");

      if (user.hasRole(role)) {
        context.success();
      } else {
        context.failure(AuthenticationFlowError.ACCESS_DENIED);
      }
      break;
    case "client-2":
      var role = authenticationSession.getClient().getRole("role-2");

      if (user.hasRole(role)) {
        context.success();
      } else {
        context.failure(AuthenticationFlowError.ACCESS_DENIED);
      }
      break;
    case "client-3":
      var role = authenticationSession.getClient().getRole("role-3");

      if (user.hasRole(role)) {
        context.success();
      } else {
        context.failure(AuthenticationFlowError.ACCESS_DENIED);
      }
      break;
    default:
      context.success();
  }
}
```

**Comment by vitorcont** [comment]
> > if a user has access to a client. This script pulls the user session, verifies which client he is loging into and validates the needed role.
> > To add the custom script just follow the instructions at the [documentation](https://www.keycloak.org/docs/latest/server_development/#_script_providers)
> 
> @vitorcont would this work if user is authenticated for the first time ?

@KhasDenis 
If he is authenticating through a IDP and the Post Login Flow has been correctly setup, yes it does works
Currently, I have a deployed keycloak application that is using the same script model to perform client verifications

What i've done is a workaround, as @cgeorgilakis mentioned above, the clients should have the options to decide about the flow, not the IDP

**Comment by KhasDenis** [comment]
@cgeorgilakis @vitorcont 
Yes I understand that it's only workaround and that client must decide. But my question is if "first broker login" flow creates user if not already exists in keycloak and "post login flow" will be called after that then user will not have neither of the "role-x" and first login must fail ? After that existing keycloak user will be assigned to corresponding role and flow will work. Question just to my learning as we have so many clients I think this workaround is not something we could use.

Also wondering why it is still in documentation https://www.keycloak.org/docs/latest/server_development/#where-to-add-script-authenticator. That flow example is exactly where problem is.

**Comment by vitorcont** [comment]
> @cgeorgilakis @vitorcont Yes I understand that it's only workaround and that client must decide. But my question is if "first broker login" flow creates user if not already exists in keycloak and "post login flow" will be called after that then user will not have neither of the "role-x" and first login must fail ? After that existing keycloak user will be assigned to corresponding role and flow will work. Question just to my learning as we have so many clients I think this workaround is not something we could use.
> 
> Also wondering why it is still in documentation https://www.keycloak.org/docs/latest/server_development/#where-to-add-script-authenticator. That flow example is exactly where problem is.

I see, well in this use case, if you try to login to a client-x that needs the role-x and the user has just been created on "first broker login" with no permissions, yes it will fail
<b>However</b>, if you add a [Mapper](https://www.keycloak.org/docs/latest/server_admin/#_mappers) to your IDP that conditionally adds a role to a User, based on a SAML Property or OpenID Access Token Property, it will work (thats my use case). 
On user creation, during "first login flow" the role will be added, and then on the "post login flow" the role will be validated

**Comment by blevine** [comment]
> Although step-authedication ([#10120](https://github.com/keycloak/keycloak/discussions/10120)) is an important feature added in Keycloak, it did not solve this bug. Not all client authorization is related with acr.
> 
> However, I will test with step-authedication and users from external Identity Providers.

In fact, step-up authentication doesn't work when there is an IdP redirect in the flow. I've opened https://github.com/keycloak/keycloak/issues/25335 for this.

**Comment by cgeorgilakis** [comment]
> > Although step-authedication ([#10120](https://github.com/keycloak/keycloak/discussions/10120)) is an important feature added in Keycloak, it did not solve this bug. Not all client authorization is related with acr.
> > However, I will test with step-authedication and users from external Identity Providers.
> 
> In fact, step-up authentication doesn't work when there is an IdP redirect in the flow. I've opened #25335 for this.

It is the same problem as using Username Password form and select an Identity Provider.
My PR solves both ways to login via Identity Provider.

**Comment by JaimySmets** [comment]
I've had a similar requirement, where I want to redirect the authenticated user to a different application using action tokens to edit their session. Similar as described in the action-token [`keycloak-quickstart`](https://github.com/keycloak/keycloak-quickstarts/tree/latest/extension/action-token-authenticator) extension. This did not work after an external idp redirect, as described in this issue. As a post-login flow it would work fine, but it does depend on the client and not the idp.

However, the following workaround worked for me. Perhaps it may help others:

1. Put the authentication step into its own authentication flow
2. Use the authentication flow as a post-login in the idp
3. Assign a specific default client scope to the clients that should perform this authenticator
4. In the authenticator, check if the client has this specific scope assigned or just complete with success
```java
ClientScopeModel myScope = authSession.getClient().getClientScopes(true).get("my-custom-scope");
if (myScope == null) {
    // The default scope was not assigned. Authenticator should pass-through.
    context.success();
    return;
}
// Else perform the custom authentication flow
...
context.challenge(challenge);
```

**Comment by jonaskello** [comment]
Also tried to set this up today, took a few hours before I realised it dit not work as expected. What I wanted was a simple role check and then deny access, and it works for cookie and form but not identity provider redirect. Now that I finally found this issue I can at least stop trying to make it work for now.

**Comment by sschu** [comment]
@jonaskello If your check is not client-specific, you could still add it to an IDP post-login flow.

**Comment by cgeorgilakis** [comment]
> Adding to important for now as lots of people are interested and looks like a limitation. We may need to re-consider as not 100% sure about effort to properly handle everything...

As mentioned before, this is not client specific flow. The regular scenario is having different browser flow for specific client (acr, deny access based on role, attribute).

**Comment by sonOfRa** [comment]
We're also currently encountering this issue.
We have some clients that enforce 2FA on login *except* if the user is from an IdP. The IdP of that realm is considered trusted because it enforces secure login methods like MFA or passkeys for every user. So we set up this loa flow:
![image](https://github.com/user-attachments/assets/b1d05f52-0ea1-475a-985b-2d87a1b634b7)

Our expectation is that users logged in with only username+password have a LoA of 1, users additionally logged in with an OTP have a LoA of 2, and users logged in through our IdP have a LoA of 3.

For non-IdP users, this flow works as expected: If a client requests a high LoA, the user is requested to provide a second factor, even if they already have an SSO session in a lower LoA client.

In the IdP scenario however, things do *not* work as expected. Logging in directly to any client works fine. But in the SSO scenario (existing session in client with low/no LoA requirement, also log in to high LoA client), the user is presented with this dialog:
![image](https://github.com/user-attachments/assets/10caf2e2-a915-4424-a513-2f0caae0b520), despite having an existing login session with the "fakebook" IdP.

**Comment by sonOfRa** [comment]
There seems to be a workaround, but I'm not quite sure why it functions the way it functions yet. For the browser flow, we can still use this flow:
![image](https://github.com/user-attachments/assets/4fd90d9e-19c7-4493-80d7-cf5c58e2ee86)
Note the *empty* LoA-3 condition at the bottom. Its presence is critical.
Together with this post-broker-login-flow:
![image](https://github.com/user-attachments/assets/03e18ba5-bab9-422f-89d6-7d4bcf99781f)
We can now achieve proper SSO with LoA for our IdP login - the users are treated as having a high LoA.
I also tried setting the configured LoA for the post-broker-flow to 1 instead of 3. This causes the IdP being treated as a lower LoA, and the user is asked to configure (or enter) their TOTP credential when they try to access a client with a higher configured LoA.

**Comment by mposolda** [comment]
Sorry for late review. This issue somehow fell apart between other things...

I am changing this to a Feature-request rather than a bug. The `Identity provider redirector` authenticator is meant to address the use-case of redirect to the IDP. However it was not meant for the use-case like `Continue to the browser flow after IDP login and mark the "Identity provider redirector" authenticator as successful and continue with the authentication flow from there`. Using this would make things more fragile and complex (the authentication flows unfortunately already are quite complex) . This could be seen in the linked PR (which makes things even more complex than they are and has lots of test failures). For continue to login after successful IDP login, there is "Post broker login flow". We may possibly need to improve on the documentation for this to make this more clear.

However I appreciate that RFE makes sense as most of the use-cases here are valid. If I summary it correctly, the use-cases might be like this:

- Make sure that users always need to authenticate with OTP after login with identity provider my-idp - This use-case should be already possible to handle with the post-broker login flow. You can configure "Post broker login flow" for the IDP and add just `OTP Form` authenticator as `REQUIRED` .

- When authenticating to Keycloak and the login is done with the IDP `my-idp`, then the users, which are authenticating to client `client-a` are also requested to authenticate with the OTP on Keycloak side after the IDP login was successfully finished. However when authenticating to client `client-b`, the users are authenticated to Keycloak right-away after login to identity provider `my-idp` without need to authenticate with the OTP. In other words, make sure that some additional authentication steps need to be performed on Keycloak side after IDP login, but those additional steps should depend on the client requesting authentication (not on the IDP).

I believe this use-case could be addressed by:

  1) Implementing the authentication condition like `Condition - client scope`. The condition will be triggered if the configured client scope is present. In this case, the `Post broker login flow` can look like this:
  ```
  Subflow1 - CONDITIONAL
    Condition - client scope REQUIRED
    OTP Form - REQUIRED  
  ```
  When the `condition - client scope` will be configured with client scope `foo`, then it might be possible to add this client scope `foo` as the default client scope to client `client-a` (and all other clients for which the OTP should be requested), but not add it to other clients like `client-b` where this is not requested

  
  2) Something similar like `Condition - client role` . This will be true when client has specified role `foo-role` specified on itself. This role is purely used as a "marker role". Basically just the fact that client has the specified client role of specified name `foo-role` is sufficient for the condition to pass (The user himself, who is authenticated, won't need to have this role).  
  
We have similar conditions in the client policies as well (`ClientScopesCondition` or `ClientRolesCondition`). Could something like this work to address the use-case? If yes, the PR with such authentication flow conditions would be welcome. IMO the (1) is preferred and more useful in general.


  3) Maybe it is possible to achieve the use-case already with latest Keycloak 26.1 (not yet released) by using the step-up authentication. The Keycloak 26.1 and latest Keycloak nightly introduces `Minimum authentication level` option as an option on the client (Thanks again to @sonOfRa for contributing this). I wonder it might be possible to configure the post-broker login flow with something like this:
  ```
    Subflow1 - CONDITIONAL
      Condition - LoA REQUIRED (level 2)
      OTP Form - REQUIRED
  ```
  
  
  And then configure `Minimum authentication level` as level 2 for the client `client-a`. But keep the default level on `client-b`. This means that condition would be triggered just for `client-a` when level 2 is requested and hence the OTP will be requested for such client. I am not 100% confident that this would work (maybe will require some more tweaks in the browser flow). @sonOfRa Maybe you know or tried already something like this (not 100% sure based on your last comment), so feel free to comment if you think this can or cannot work.
  
  
  IMO the (1) will be preferred as the condition for client scope will be more than useful for additional use-cases (not just for the action after IDP login).

**Comment by mposolda** [comment]
I am trying some prototyping here with the client-scopes condition. I believe that it can be useful for other use-cases when some flow/subflow is requested just for some client (or group of clients). I hope to send PR soon.

**Comment by cgeorgilakis** [comment]
> Sorry for late review. This issue somehow fell apart between other things...
> 
> I am changing this to a Feature-request rather than a bug. The `Identity provider redirector` authenticator is meant to address the use-case of redirect to the IDP. However it was not meant for the use-case like `Continue to the browser flow after IDP login and mark the "Identity provider redirector" authenticator as successful and continue with the authentication flow from there`. Using this would make things more fragile and complex (the authentication flows unfortunately already are quite complex) . This could be seen in the linked PR (which makes things even more complex than they are and has lots of test failures). For continue to login after successful IDP login, there is "Post broker login flow". We may possibly need to improve on the documentation for this to make this more clear.
> 
> However I appreciate that RFE makes sense as most of the use-cases here are valid. If I summary it correctly, the use-cases might be like this:
> 
> * Make sure that users always need to authenticate with OTP after login with identity provider my-idp - This use-case should be already possible to handle with the post-broker login flow. You can configure "Post broker login flow" for the IDP and add just `OTP Form` authenticator as `REQUIRED` .
> * When authenticating to Keycloak and the login is done with the IDP `my-idp`, then the users, which are authenticating to client `client-a` are also requested to authenticate with the OTP on Keycloak side after the IDP login was successfully finished. However when authenticating to client `client-b`, the users are authenticated to Keycloak right-away after login to identity provider `my-idp` without need to authenticate with the OTP. In other words, make sure that some additional authentication steps need to be performed on Keycloak side after IDP login, but those additional steps should depend on the client requesting authentication (not on the IDP).
> 
> I believe this use-case could be addressed by:
> 
> 1. Implementing the authentication condition like `Condition - client scope`. The condition will be triggered if the configured client scope is present. In this case, the `Post broker login flow` can look like this:
> 
> ```
> Subflow1 - CONDITIONAL
>   Condition - client scope REQUIRED
>   OTP Form - REQUIRED  
> ```
> 
> When the `condition - client scope` will be configured with client scope `foo`, then it might be possible to add this client scope `foo` as the default client scope to client `client-a` (and all other clients for which the OTP should be requested), but not add it to other clients like `client-b` where this is not requested
> 
> 2. Something similar like `Condition - client role` . This will be true when client has specified role `foo-role` specified on itself. This role is purely used as a "marker role". Basically just the fact that client has the specified client role of specified name `foo-role` is sufficient for the condition to pass (The user himself, who is authenticated, won't need to have this role).
> 
> We have similar conditions in the client policies as well (`ClientScopesCondition` or `ClientRolesCondition`). Could something like this work to address the use-case? If yes, the PR with such authentication flow conditions would be welcome. IMO the (1) is preferred and more useful in general.
> 
> 3. Maybe it is possible to achieve the use-case already with latest Keycloak 26.1 (not yet released) by using the step-up authentication. The Keycloak 26.1 and latest Keycloak nightly introduces `Minimum authentication level` option as an option on the client (Thanks again to @sonOfRa for contributing this). I wonder it might be possible to configure the post-broker login flow with something like this:
> 
> ```
>   Subflow1 - CONDITIONAL
>     Condition - LoA REQUIRED (level 2)
>     OTP Form - REQUIRED
> ```
> 
> And then configure `Minimum authentication level` as level 2 for the client `client-a`. But keep the default level on `client-b`. This means that condition would be triggered just for `client-a` when level 2 is requested and hence the OTP will be requested for such client. I am not 100% confident that this would work (maybe will require some more tweaks in the browser flow). @sonOfRa Maybe you know or tried already something like this (not 100% sure based on your last comment), so feel free to comment if you think this can or cannot work.
> 
> IMO the (1) will be preferred as the condition for client scope will be more than useful for additional use-cases (not just for the action after IDP login).

The most important for as is that Keycloak as a proxy must support MFA for federated users. My PR is trying to fix this together with other client flow specific actions like OTP, deny access with continuing flow after user is login via IdP.
Based on [OpenID Connect Core 1.0](https://openid.net/specs/openid-connect-core-1_0-final.html), [JSON Web Token (JWT) Profile for OAuth 2.0 Access Tokens](https://datatracker.ietf.org/doc/rfc9068/) and [OAuth 2.0 Step Up Authentication Challenge Protocol](https://datatracker.ietf.org/doc/rfc9470/) MFA in id token, access token and token introspection should be able to requested via : 

- static configuration based on [mentioned PR](https://github.com/keycloak/keycloak/pull/33205)
- acr claim
- acr_values

As I understand Keycloak will supports all these ways in version 26.1 . We will investigate further this later and details are out of scope of this PR.

However, @mposolda Keycloak version 26.1 will support all the supported MFA ways also for federated users? Will it be done via development / configuration? How? 
I believe that this is the important investigation action related to the proposed solution.

**Comment by cgeorgilakis** [comment]
I have forgoten to mentioned that each client may (or may not) use MFA in differnet way.

**Comment by pulkit10251** [comment]
Hello @cgeorgilakis
I also have a usecase in which we have different sca methods, like delegation [ redirect to external idp ] and proxy [custom username and password form]. User will conditionally move to either one of the flow. Once the authentication is completed, I need to perform some specific set of actions irrespective of the sca-method chosen, but since idp-redirection flow is not resumed in browser I have to mention the same outer flow additionally in post-broker login. 

So its not a blocker for us but yes the initial suggestion that identityProvider flow can continue in browser seems very ideal for my usecase. I hope we can still check if this is feasible or not. I am sure such usecases are present and it could be a valuable addition.

**Comment by mposolda** [comment]
@cgeorgilakis @pulkit10251  Thanks for the feedback!

I've created the dedicated issue for the client scope condition #36081, instead of directly referencing this issue with my addition of conditional client scope.

I believe that most of the use-cases outlined here are addressable with the mentioned issues added in 26.1 #36081, #16884 and #35231 (The last one is conditional authenticator to check if the subflow was executed). However I am keeping this issue open for the further reference in case that we want to revisit the idea of continue with the browser flow after identity provider login. I believe this may require some polishing and some more though if we go that path as I fear this can have some corner cases and potential regressions coming from this. Some more points:

- The `Identity provider redirector` authenticator was supposed to be used just for the redirect to the IDP. It was not supposed to be used as a `placeholder in the authentication flow representing IDP login`. One note is that IDP login can be still used even if `Identity provider redirector` is not used at all in the authentication flow (User can click on the "login with IDP" button from the username/password page or from username page etc). If we revisit this issue, it may require some configuration option (maybe on the `Identity provider redirector` authenticator) to specify if return to the `browser` flow after IDP login is desired behaviour.

- There are failing tests in the linked PR https://github.com/keycloak/keycloak/pull/12891, which may indicate that some currently supported Keycloak functionality is broken

- Agree with the point by @pulkit10251 that post login flow approach requires some duplicated configuration of the authentication flows. Possible improvement might be to support "Re-usable subflows" when administrator can configure subflow and then reference the same subflow from more authentication flows (EG. reference the same subflow from `browser` and `post login flow`).

- Agree that `browser` flow can make things more clear (especially in the use-cases with the step-up authentication involved) where it is possible to declare levels etc in the single flow `browser` rather than dealing with multiple flows. I think that most of the step-up/ACR related use-cases are possible to cover with the combination of "browser" flow and IDP login together with "post login flow approach" and with the new additions in Keycloak 26.1. But if you have example of the use-cases, which are not possible, the feedback with further comments is welcome

- > @mposolda Keycloak version 26.1 will support all the supported MFA ways also for federated users? Will it be done via development / configuration? How? I have forgoten to mentioned that each client may (or may not) use MFA in differnet way.

I think this use-cases can work with post broker flow configured in a way like for example:

```
- Allow authenticator - REQUIRED
- Conditional subflow for scope `otp-only` - CONDITIONAL
-- condition - client scope `otp-only` - REQUIRED
-- OTP Form - REQUIRED
- Conditional subflow for scope `otp-or-webauthn` - CONDITIONAL
-- Condition - client scope `otp-or-webauthn` - REQUIRED
-- OTP Form ALTERNATIVE
-- WebAuthn ALTERNATIVE
```
Some tweaking may be needed in the `otp-or-webauthn` subflow if you also want to cover use-case when user doesn't have any of those 2-factor credentials on this account and you want to him register one of them . Some documentation is being added in 26.1 regarding post login flow and also regarding 2-factor authentication example with the use of `condition - subflow executed` (new condition added in 26.1 with the issue #35231 )

### Some more alternatives

- Ability to have `post broker login override` flow configurable per client. Currently clients have ability to override `browser` flow and `direct grant` flow, but not more. The `post login flow` can be another thing. It will have preference over the flow configured on the IDP side if it is used. The limitation is, that client will need to have same `post login flow` for all the IDPs (current approach with `post login flow` configurable on the IDP side means that every IDP can have different `post login flow` as every IDP may have different level of trust). Matrix of post login flow for every pair `client, IDP` sounds like even more complexity, so hopefully possible to avoid

- re-usable flows as outlined above - but this can be harder to do as it may require changes in the admin console UI, admin REST API, model SPI etc.

- Authentication policies - different approach to the authentication where administrator might be able to declare in a more simple way something like `User is required to login with: (identity-provider OR username/password) AND (otp OR WebAuthn OR Recovery-codes)` instead of dealing with the authentication flows. Could be quite complex and not sure when we go into this.

**Comment by mposolda** [comment]
For the reference: Another improvement related to step-up authentication, which is going to be added soon https://github.com/keycloak/keycloak/issues/24297 . However we probably miss Keycloak 26.1 with this one.

**Comment by jbman** [comment]
What about a new **post browser authentication flow**, which is also overridable per client? The default could be empty/not set, so that this is fully backwards compatible. It would be executed as final flow after any post Idp flow or after the browser authorization flow (if no Idp flow was executed)
Basically it allows splitting an existing browser login flow into two parts. 

We  could make use of a default post browser login and fill it with MFA conditions and steps which are currently added two-times identically: at post IdP login flow and browser flow (at some installations we operate).

**Comment by cgeorgilakis** [comment]
> What about a new **post browser authentication flow**, which is also overridable per client? The default could be empty/not set, so that this is fully backwards compatible. It would be executed as final flow after any post Idp flow or after the browser authorization flow (if no Idp flow was executed) Basically it allows splitting an existing browser login flow into two parts.
> 
> We could make use of a default post browser login and fill it with MFA conditions and steps which are currently added two-times identically: at post IdP login flow and browser flow (at some installations we operate).

This could be ideal if someone could implement it.
It provides:

- Possibility for same funcionality for Keycloak and federated Users
- less and more clear configuration
- Per client configuration

**Comment by cgeorgilakis** [comment]
> @cgeorgilakis @pulkit10251 Thanks for the feedback!
> 
> I've created the dedicated issue for the client scope condition #36081, instead of directly referencing this issue with my addition of conditional client scope.
> 
> I believe that most of the use-cases outlined here are addressable with the mentioned issues added in 26.1 #36081, #16884 and #35231 (The last one is conditional authenticator to check if the subflow was executed). However I am keeping this issue open for the further reference in case that we want to revisit the idea of continue with the browser flow after identity provider login. I believe this may require some polishing and some more though if we go that path as I fear this can have some corner cases and potential regressions coming from this. Some more points:
> 
> * The `Identity provider redirector` authenticator was supposed to be used just for the redirect to the IDP. It was not supposed to be used as a `placeholder in the authentication flow representing IDP login`. One note is that IDP login can be still used even if `Identity provider redirector` is not used at all in the authentication flow (User can click on the "login with IDP" button from the username/password page or from username page etc). If we revisit this issue, it may require some configuration option (maybe on the `Identity provider redirector` authenticator) to specify if return to the `browser` flow after IDP login is desired behaviour.
> * There are failing tests in the linked PR [Continue client browser flow after User login from Identity Provider #12891](https://github.com/keycloak/keycloak/pull/12891), which may indicate that some currently supported Keycloak functionality is broken
> * Agree with the point by @pulkit10251 that post login flow approach requires some duplicated configuration of the authentication flows. Possible improvement might be to support "Re-usable subflows" when administrator can configure subflow and then reference the same subflow from more authentication flows (EG. reference the same subflow from `browser` and `post login flow`).
> * Agree that `browser` flow can make things more clear (especially in the use-cases with the step-up authentication involved) where it is possible to declare levels etc in the single flow `browser` rather than dealing with multiple flows. I think that most of the step-up/ACR related use-cases are possible to cover with the combination of "browser" flow and IDP login together with "post login flow approach" and with the new additions in Keycloak 26.1. But if you have example of the use-cases, which are not possible, the feedback with further comments is welcome
> * > @mposolda Keycloak version 26.1 will support all the supported MFA ways also for federated users? Will it be done via development / configuration? How? I have forgoten to mentioned that each client may (or may not) use MFA in differnet way.
> 
> I think this use-cases can work with post broker flow configured in a way like for example:
> 
> ```
> - Allow authenticator - REQUIRED
> - Conditional subflow for scope `otp-only` - CONDITIONAL
> -- condition - client scope `otp-only` - REQUIRED
> -- OTP Form - REQUIRED
> - Conditional subflow for scope `otp-or-webauthn` - CONDITIONAL
> -- Condition - client scope `otp-or-webauthn` - REQUIRED
> -- OTP Form ALTERNATIVE
> -- WebAuthn ALTERNATIVE
> ```
> 
> Some tweaking may be needed in the `otp-or-webauthn` subflow if you also want to cover use-case when user doesn't have any of those 2-factor credentials on this account and you want to him register one of them . Some documentation is being added in 26.1 regarding post login flow and also regarding 2-factor authentication example with the use of `condition - subflow executed` (new condition added in 26.1 with the issue #35231 )
> 
> ### Some more alternatives
> * Ability to have `post broker login override` flow configurable per client. Currently clients have ability to override `browser` flow and `direct grant` flow, but not more. The `post login flow` can be another thing. It will have preference over the flow configured on the IDP side if it is used. The limitation is, that client will need to have same `post login flow` for all the IDPs (current approach with `post login flow` configurable on the IDP side means that every IDP can have different `post login flow` as every IDP may have different level of trust). Matrix of post login flow for every pair `client, IDP` sounds like even more complexity, so hopefully possible to avoid
> * re-usable flows as outlined above - but this can be harder to do as it may require changes in the admin console UI, admin REST API, model SPI etc.
> * Authentication policies - different approach to the authentication where administrator might be able to declare in a more simple way something like `User is required to login with: (identity-provider OR username/password) AND (otp OR WebAuthn OR Recovery-codes)` instead of dealing with the authentication flows. Could be quite complex and not sure when we go into this.

Thanks @mposolda for all this information. 
All you mentionted is a lot of configuration that the best way is to be done when version 26.1.0 is released.
Later, we will check that latest Keycloak support MFA for federated users and we will come back for any problems.

As I have mentioned in my previous comment, we like the @jbman proposal.

**Comment by aymone** [comment]
After 3 years this is still an issue.

**Comment by cgeorgilakis** [comment]
@mposolda I have tested ConditionalClientScopeAuthenticator with version 26.4.2 and the problem continues to exist.
I could try to rebase the PR unless you have another proposal for fixing the issue.

**Comment by Spliterash** [comment]
Why does this issue even exist, and why hasn't it been fixed yet? It's literally nonsense. After a social step, there may be additional steps. Why did someone decide that they should be ignored?

Sorry for the passive aggression, but I'm bursting with emotion. I never even thought such a problem could arise.

**Comment by dafenix** [comment]
I've implemented a PR for this. Here's my suggestion: https://github.com/keycloak/keycloak/pull/46116
