### ISSUE TITLE
backend port added to frontend URL

### ISSUE THREAD

**Issue by danelowe** [keycloak/keycloak#11050]
### Describe the bug

If I build on 17.0.0 with same procedure, the frontend endpoints don't have ports in them. If I build with 17.0.1, they do

### Version

17.0.1

### Expected behavior

```json
{"issuer":"http://auth.test/realms/master","authorization_endpoint":"http://auth.test/realms/master/protocol/openid-connect/auth","token_endpoint":"http://localhost/realms/master/protocol/openid-connect/token","introspection_endpoint":"http://localhost/realms/master/protocol/openid-connect/token/introspect","end_session_endpoint":"http://auth.test/realms/master/protocol/openid-connect/logout","frontchannel_logout_session_supported":true,"frontchannel_logout_supported":true,"jwks_uri":"http://localhost/realms/master/protocol/openid-connect/certs","grant_types_supported":["authorization_code","implicit","refresh_token","password","client_credentials","urn:ietf:params:oauth:grant-type:device_code","urn:openid:params:grant-type:ciba"],"response_types_supported":["code","none","id_token","token","id_token token","code id_token","code token","code id_token token"],"response_modes_supported":["query","fragment","form_post","query.jwt","fragment.jwt","form_post.jwt","jwt"],"registration_endpoint":"http://localhost/realms/master/clients-registrations/openid-connect","token_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post","tls_client_auth","client_secret_jwt"],"token_endpoint_auth_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"scopes_supported":["openid","address","email","roles","microprofile-jwt","offline_access","profile","phone","web-origins"],"resource_registration_endpoint":"http://auth.test/realms/master/authz/protection/resource_set","permission_endpoint":"http://auth.test/realms/master/authz/protection/permission","policy_endpoint":"http://auth.test/realms/master/authz/protection/uma-policy"}
```

### Actual behavior

```json
{"issuer":"http://auth.test:8080/realms/master","authorization_endpoint":"http://auth.test:8080/realms/master/protocol/openid-connect/auth","token_endpoint":"http://localhost:8080/realms/master/protocol/openid-connect/token","introspection_endpoint":"http://localhost:8080/realms/master/protocol/openid-connect/token/introspect","end_session_endpoint":"http://auth.test:8080/realms/master/protocol/openid-connect/logout","frontchannel_logout_session_supported":true,"frontchannel_logout_supported":true,"jwks_uri":"http://localhost:8080/realms/master/protocol/openid-connect/certs","grant_types_supported":["authorization_code","implicit","refresh_token","password","client_credentials","urn:ietf:params:oauth:grant-type:device_code","urn:openid:params:grant-type:ciba"],"response_types_supported":["code","none","id_token","token","id_token token","code id_token","code token","code id_token token"],"response_modes_supported":["query","fragment","form_post","query.jwt","fragment.jwt","form_post.jwt","jwt"],"registration_endpoint":"http://localhost:8080/realms/master/clients-registrations/openid-connect","token_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post","tls_client_auth","client_secret_jwt"],"token_endpoint_auth_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"scopes_supported":["openid","address","email","roles","microprofile-jwt","offline_access","profile","phone","web-origins"],"resource_registration_endpoint":"http://auth.test:8080/realms/master/authz/protection/resource_set","permission_endpoint":"http://auth.test:8080/realms/master/authz/protection/permission","policy_endpoint":"http://auth.test:8080/realms/master/authz/protection/uma-policy"}
```

### How to Reproduce?

```shell
mvn clean install -DskipTestsuite -DskipExamples -DskipTests -e
cd quarkus 
mvn clean install -DskipTests
java -jar server/target/lib/quarkus-run.jar start-dev --hostname=auth.test
curl -vvv http://localhost:8080/realms/master/.well-known/uma2-configuration
```

**Comment by pedroigor** [comment]
@danelowe Could you try setting the `proxy` option. For instance, `--proxy edge`?

When using the hostname, it is expected you are running behind a proxy so that the port defaults to the HTTP/HTTPS ports and not from the request.

**Comment by pedroigor** [comment]
@danelowe @biertz Setting the `hostname` is going to change the host part of the URL only. The port is still resolved from the request.

@biertz If running 18 and running the server as follows:

```
./kc.sh start --hostname mykeycloak --proxy edge
```

The frontend URLs are using the default ports (80 in this case).

**Comment by biertz** [comment]
> @biertz If running 18 and running the server as follows:
> 
> ```
> ./kc.sh start --hostname mykeycloak --proxy edge
> ```
> 
> The frontend URLs are using the default ports (80 in this case).
@pedroigor  How would I force it to use 443? Or is it a bug? I thought that if I specify that KC is running behind a TLS terminating reverse proxy, it would know that I want 443 frontend urls.

**Comment by pedroigor** [comment]
If your proxy is forwarding the `443` port then you have the URLs based on 443 (internally it is resolved to -1 indicating it is the default protocol port).

**Comment by biertz** [comment]
That was indeed it, thanks! Setup behind doubled proxy which messed everything up. Though I still don't understand why KC_HOSTNAME_PORT=443 wouldn't have forced it to take 443 instead of the forwarded port.

**Comment by Rosslu** [comment]
did anyone get this to work? I'm on 18.0.2 and using --proxy edge but it's still adding port 80 instead of port 443. even trying to force the header on the proxy side doesn't seem to work.

**Comment by biertz** [comment]
@Rosslu Are you using multiple proxies, like an edge router behind a HAproxy or something similar? If so, ensure that they all forward the correct port.

**Comment by savasdd** [comment]
good bu not
