### ISSUE TITLE
non TLS connection: Blank admin console page due to missing 3p-cookies/step1.html resource

### ISSUE THREAD

**Issue by psytester** [keycloak/keycloak#11170]
### Describe the bug

In my setup, the TLS is done in TLS Apache endpoint as reverse proxy, thus I did not setup any TLS stuff in keycloak.

Usage of admin console is done in internal network directly.

I get a blank admin console page after login
Root cause: The resource 3p-cookies/step1.html will be loaded as TLS connection with https but that fails on port 8080
```GET https://10.1.93.60:8080/auth/realms/master/protocol/openid-connect/3p-cookies/step1.html?version=9qn3t```

It does not happen, if I set the "hidden" property `hostname-strict-https=false`
The resource 3p-cookies/step1.html will be loaded successfully as normal http connection
```GET http://10.1.93.60:8080/auth/realms/master/protocol/openid-connect/3p-cookies/step1.html?version=9qn3t```
and the admin console page is displayed

My configuration:
```
# I do NOT set `hostname` nor `hostname-admin`

# remaining possible related settings in use are
proxy=edge
hostname-strict=false

http-enabled=true
http-relative-path=/auth

# How disable strict https
# https://github.com/keycloak/keycloak/discussions/10740
# Undocumented config parameter
hostname-strict-https=false
```

### Version

17.0.1

### Expected behavior

If `http-enabled=true` is used and keycloak is called with its direct IP, the admin console page is shown after login without usage of hidden property `hostname-strict-https=false`

### Actual behavior

Faulty call of resource `3p-cookies/step1.html` blocks the page usage, it loops in trying to get the whole page

**Comment by pedroigor** [comment]
@psytester This should be fixed in `18.0.0`. Now the admin URLs are built based on the request information.

**Comment by psytester** [comment]
@pedroigor I installed 18.0.0 and the error still exists.
`3p-cookies/step1.html` can not be loaded due to `https` schema.

**Comment by psytester** [comment]
I'm linking closed issue #10899 where only same workaround was provided.

**Comment by pedroigor** [comment]
@psytester It should work if you set `hostname-strict-https=false`. For instance:

```
./kc.sh start --auto-build --proxy edge --hostname-strict false --hostname-strict-https false
```

**Comment by psytester** [comment]
@pedroigor for sure `hostname-strict-https=false` is doing its job, already since 17.0.0
But I assumed the solution should look different because of your inital comment:
>Now the admin URLs are built based on the request information.

You are right. HTTPS in production is mandatory.
But in our case we have a reserve proxy in front as TLS endpoint. Admin API and Admin UI is accessable from internal network only and blocked (hopefully) in reverse proxy. And finally I will use `hostname-admin` to bind to internal management network only.

**Comment by pedroigor** [comment]
@psytester Since 18 we no longer have the `hostname-admin` option. Now the admin URL is based on the information from the request.

However, the login page is based on the frontend URL so if you are using the internal network you should still be redirected to the public URL.

**Comment by piotrooo** [comment]
I'm still facing with this error...

I have a simple configuration:

```
export default new Keycloak({
    url: 'http://0.0.0.0:8080/auth',
    realm: 'testrealm',
    clientId: 'web-app',
})
```

then init call:

```
keycloak.init({
    onLoad: 'check-sso',
    silentCheckSsoRedirectUri: `${window.location.origin}/check-sso`,
    checkLoginIframe: false,
}).then(value => {
    console.log(value)
    renderApp()
}).catch(console.error)
```

Nothing complicated.
In web console:

![Zrzut ekranu z 2022-05-07 18-55-32](https://user-images.githubusercontent.com/2005054/167264224-8e4ea800-74e9-4b97-8361-3992c814da65.png)

**Comment by pedroigor** [comment]
@piotrooo Could you please try changing `url: 'http://0.0.0.0:8080/auth'` to `url: 'http://localhost:8080/auth`?

**Comment by Abuesy** [comment]
Hi All, i am facing a similar issue. I am also using Keycloak 18.0.0. It is running in kubernetes in prod-mode. And i am also behind a reverseproxy. 

When keycloak starts i can see the default homepage. But when i click on Admin-console i get a blanc-page.
I aslo tried **(--hostname-strict-https false --hostname-strict false --http-enabled true)** but to no avail. 

When i go to: https://myhostname:7443/admin/master/console/config i see the following:
{"realm":"master","auth-server-url":"https://localhost:8443/","ssl-required":"external","resource":"security-admin-console","public-client":true,"confidential-port":0}

And when i check the logging of keycloak when starting up, i see the following:
_2022-06-26 16:50:16,793 INFO  [io.quarkus] (main) Keycloak 18.0.0 on JVM (powered by Quarkus 2.7.5.Final) started in 7.350s. Listening on: http://0.0.0.0:8080/ and https://0.0.0.0:8443/                     │
2022-06-26 16:50:16,794 INFO  [io.quarkus] (main) Profile prod activated._

**Comment by Abuesy** [comment]
Hi,

I got it to work. I changed my KC_HOSTNAME from (localhost) to (my-linux-hostname)

First let me describe my environment:
I am running k3s on a Linux machine. This Linux-machine is reachable from the outside through 'my-linux-hostname:7443'.  
I have Keycloak running inside a pod, reachable on port 8443. And i have a load-balancer-service within k3s that connects port 7443 (linux) to 8443 (keycloak).
In the beginning i configured KC_HOSTNAME to **localhost** (or to 127.0.01). Because from keycloak point of view its hostname is 'localhost' since its residing inside a pod. So the welcome page worked fine, but when i was forwarded to the admin-page i got a white-page.

But when i changed my KC_HOSTNAME to **my-linux-hostname**, and KC_HOSTNAME_PORT to **7443**, everything worked fine.

And it doesnt matter whether i used KC_PROXY=edge or KC_PROXY=passthrough. Both are working.

And it worked on Chrome

**Comment by pedroigor** [comment]
@Abuesyz Thanks. In this case, the `hostname-port` makes sense because you are exposing the server using a port other than the default: `8443`.

**Comment by psytester** [comment]
@pedroigor You closed my issue without any reference to a fix nor documentation add-on, thus I installed fresh 18.0.2 release to give it a try because of come back of `hostname-admin`.
Setting `hostname-admin=mylocalnetworkhostname` ....
Unfortunately same error as before, if I do not use `hostname-strict-https=false` the `openid-connect/3p-cookies/step1.html` request is sent as TLS on non-TLS port: `https://10.1.93.60:8080/auth/realms/master/protocol/openid-connect/3p-cookies/step1.html`

Did I miss something else?
UI issue keycloak/keycloak-admin-ui/issues/2703 from @thomasdarimont looks similar, but there `hostname-strict-https=true` is used and it's labeled as upcomming 19.0.0 release.



Once again, my setup is:
a HA cluster with two nodes and keycloak configuration only from internal network without TLS usage at default HTTP port 8080 due to `http-enabled=true`.

Intitial admin UI call is once at single node IP: `http://kc_IP_of_node_1_or_2:8080/auth/admin`
or at cluster IP `http://kc_IP_of_loadbalancer:8080/auth/admin`
always without TLS @ port 8080
but routes to TLS @ port 8080 just for `3p-cookies/step1.html` 😢

**Comment by psytester** [comment]
> Please, let me know if it works for you.

👍 
With new section in documentation I'm fine!

https://www.keycloak.org/server/hostname#_accessing_keycloak_in_production_mode_using_http is doing its job.

**Comment by AustinOyugi** [comment]
@pedroigor  Hello, I'm also facing a similar issue while using keycloak 20.0 with it's kubernetes Operator version 20.0

I have keycloak running on a reverse proxy... 

I've set HTTP enabled to false
I've set the proxy type to edge 
I've set strict back channel to false

The hostname is the public domain name but without the scheme.

when I exec into the pod and see the set env variables;
KC_STRICT_HTTPS=false
KC_HOSTNAME_STRICT=false
KC_HOSTNAME_STRICT_BACKCHANNEL=false
KC_PROXY=edge
KC_HTTP_ENABLED=true


But in the logs I'm still seeing 
Strict HTTPS: true

When I visit the hostname I can see the main Keycloak landing page, but when I click on the administration console,  I'm stuck at loading the admin console.

Is there something I've missed in the configuration or something that I've done wrong?

**Comment by ogontaro** [comment]
I too was trying to run keycloak under reverse proxy and ran into problems, which led me to this thread.
I'll share the configuration that worked for me.
I was trying to run it with KC_PROXY=edge configuration.

The way it worked was to set KC_HOSTNAME_URL and KC_HOSTNAME_ADMIN_URL.
Setting KC_HOSTNAME_URL fixes the mixed content bug, and setting KC_HOSTNAME_ADMIN_URL prevents keycloak from throwing 403 errors!
