### ISSUE TITLE
Clear expired events errors

### ISSUE THREAD

**Issue by darius-m** [keycloak/keycloak#13396]
### Describe the bug

After upgrading to Keycloak 19.0.0, the following errors are logged in the server log:

```
ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-2) Failed to run scheduled task ClearExpiredEvents: java.lang.IllegalAccessError: class org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1 tried to access protected field org.keycloak.services.scheduled.ScheduledTaskRunner.task (org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1 is in unnamed module of loader 'org.keycloak.keycloak-model-legacy-private@19.0.0' @1c229870; org.keycloak.services.scheduled.ScheduledTaskRunner is in unnamed module of loader 'org.keycloak.keycloak-server-spi-private@19.0.0' @558b25b9)
        at org.keycloak.keycloak-model-legacy-private@19.0.0//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:56)
        at org.keycloak.keycloak-model-legacy-private@19.0.0//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:52)
        at org.keycloak.keycloak-model-infinispan@19.0.0//org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78)
        at org.keycloak.keycloak-model-legacy-private@19.0.0//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner.runTask(ClusterAwareScheduledTaskRunner.java:52)
        at org.keycloak.keycloak-server-spi-private@19.0.0//org.keycloak.services.scheduled.ScheduledTaskRunner.run(ScheduledTaskRunner.java:54)
        at org.keycloak.keycloak-services@19.0.0//org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
```

### Version

19.0.0-legacy

### Anything else?

The issue may be caused by the fact that this class was moved in cb81a17.

**Comment by savv** [comment]
Same here, for 19.0.0-legacy. I can reproduce simply by running:
`docker run --rm -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin quay.io/keycloak/keycloak:19.0.0-legacy`

and waiting for 5-15 minutes. I also tried the non-docker version and it has the same issue. I didn't try Quarkus / keycloak X.

**Comment by savv** [comment]
Just for any others finding this issue - keycloak 19.0.1 still has this issue.

**Comment by darius-m** [comment]
I have made a mistake - I was also referring to the legacy version. I have fixed the description.

**Comment by oteichmann** [comment]
Same issue here with version 19.0.1-legacy. Please fix.

**Comment by olivierboudet** [comment]
This seems to not be included in 19.0.2 despite the milestone set to 19.0.2.

**Comment by sschu** [comment]
Indeed. I guess this warrants a 19.0.3...

**Comment by DaMo86** [comment]
What is the exact impact of this issue, could it lead to storage or memory problems? 
We are not sure if it is acceptable to run the latest version with this bug as we do not know when we can expect 19.0.3.

**Comment by darius-m** [comment]
@ahus1, @abstractj issue #13396 is mentioned in the 19.0.2 release notes as fixed, but there have been a few messages saying that this is not the case - there have also been other issues mentioning this.

**Comment by ahus1** [comment]
I confirm that this has sadly not shipped as part of 19.0.2. I'll prepare a PR for the 19.x branch to backport this.

**Comment by ahus1** [comment]
Milestone and project assignment updated; @abstractj please review.

PR #14574 created, builds are still running.

**Comment by Juhi214-j** [comment]
We still have this error and in this mess of comments i couldnt quite read out is this fixed now or not and what do i have to to to fix this in our docker?

**Comment by sschu** [comment]
You have to update to KC 19.0.3, it is fixed there.

**Comment by hrbt11** [comment]
Faced the same problem and solved by below workaround.

In our case, somehow the username "admin" under master realm changed to some other username.
Issue resolved after creating username "admin" under master realm and assigned with admin roles.

**Comment by patateskafa** [comment]
sorry for necrobumping but the issue persists in version 26.4.0

**Comment by ahus1** [comment]
@patateskafa - if you see this happening in 26.4.0, please update to the latest patch release. If the issue persists, open a new bug issue.
