### ISSUE TITLE
[keycloak 18.0.1/19.0.2] keycloak cli export fail when enabling cache

### ISSUE THREAD

**Issue by manbobo2002** [keycloak/keycloak#14733]
### Describe the bug

```
bash-4.4$ /opt/keycloak/bin/kc.sh export --realm test --file /opt/keycloak/exported.json
JAVA_OPTS already set in environment; overriding default settings with values: -XX:+UseContainerSupport -XX:MaxRAMPercentage=50.0 -Djava.awt.headless=true -Djgroups.dns.query=keycloak-headless
2022-10-05 09:04:49,467 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: admin_fine_grained_authz
2022-10-05 09:04:49,472 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: admin2
2022-10-05 09:04:49,475 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: openshift_integration
2022-10-05 09:04:49,476 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: scripts
2022-10-05 09:04:49,478 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: token_exchange
2022-10-05 09:04:49,479 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: declarative_user_profile
2022-10-05 09:04:49,482 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: client_secret_rotation
2022-10-05 09:04:49,482 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: recovery_codes
2022-10-05 09:04:49,544 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: true
2022-10-05 09:04:55,135 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-10-05 09:04:55,272 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-10-05 09:04:55,504 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-10-05 09:04:56,893 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final
2022-10-05 09:04:57,834 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2022-10-05 09:05:07,133 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2022-10-05 09:05:07,135 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start caches
2022-10-05 09:05:07,137 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: org.infinispan.manager.EmbeddedCacheManagerStartupException: org.infinispan.commons.CacheException: Unable to start JGroups Channel
2022-10-05 09:05:07,138 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: org.infinispan.commons.CacheException: Unable to start JGroups Channel
2022-10-05 09:05:07,142 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start JGroups Channel
2022-10-05 09:05:07,142 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: no port available in range [7800 .. 7800] (bind_addr=/10.133.93.236)
2022-10-05 09:05:07,143 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.

```

but when I set `cache=local`, all are working fine.
```
bash-4.4$ /opt/keycloak/bin/kc.sh export --realm test --file /opt/keycloak/exported.json
JAVA_OPTS already set in environment; overriding default settings with values: -XX:+UseContainerSupport -XX:MaxRAMPercentage=50.0 -Djava.awt.headless=true -Djgroups.dns.query=keycloak-headless
2022-10-05 09:21:31,959 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: admin_fine_grained_authz
2022-10-05 09:21:31,971 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: admin2
2022-10-05 09:21:31,972 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: openshift_integration
2022-10-05 09:21:31,972 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: scripts
2022-10-05 09:21:31,973 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: token_exchange
2022-10-05 09:21:31,979 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: declarative_user_profile
2022-10-05 09:21:31,980 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: client_secret_rotation
2022-10-05 09:21:31,981 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: recovery_codes
2022-10-05 09:21:32,405 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: true
2022-10-05 09:21:34,142 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-10-05 09:21:34,710 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-10-05 09:21:34,964 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-10-05 09:21:36,089 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final
2022-10-05 09:21:38,911 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_23915, Site name: null
2022-10-05 09:21:50,643 INFO  [org.keycloak.services] (main) KC-SERVICES0034: Export of realm 'htm' requested.
2022-10-05 09:21:50,643 INFO  [org.keycloak.exportimport.singlefile.SingleFileExportProvider] (main) Exporting realm 'htm' into file /opt/keycloak/exported.json
2022-10-05 09:21:54,487 INFO  [org.keycloak.services] (main) KC-SERVICES0035: Export finished successfully
2022-10-05 09:21:54,869 ERROR [org.keycloak.services] (main) KC-SERVICES0010: Failed to add user 'kc-admin' to realm 'master': user with username exists
2022-10-05 09:21:55,975 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2022-10-05 09:21:55,976 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start HTTP server
2022-10-05 09:21:55,976 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: io.quarkus.runtime.QuarkusBindException
2022-10-05 09:21:55,976 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```
The sad thing is I am not able to do something
```
bash-4.4$ KC_CACHE=local /opt/keycloak/bin/kc.sh export --realm test --file /opt/keycloak/exported.json
```
which is not working

### Version

18.0.1

**Comment by vmuzikar** [comment]
@manbobo2002 Thanks for the report. Could you please confirm the issue is still valid with the latest 19.0.2?

**Comment by manbobo2002** [comment]
@vmuzikar upgraded to 19.0.2, the issue is still there

**Comment by manbobo2002** [comment]
@vmuzikar may I have any update? I think this blocks me to do something, or any alternative way or work around u could suggest?

**Comment by aaron-kunde** [comment]
I have the same issue, with versions 19.0.2 and nightly (> 19.0.3) if I enable `--cache-stack=kubernetes`. With `--cache-stack=udp` export works

**Comment by aaron-kunde** [comment]
@manbobo2002 My current work around is, to rebuild the keycloak with a working cache setting just to execute the export cli. This should not affect the current running keycloak process. But it surely feels weird.

**Comment by manbobo2002** [comment]
hi, anyone is working on this?

**Comment by tirelibirefe** [comment]
Also export-import doesn't work on Keycloak because of this problem.

**Comment by vvp1983** [comment]
change cache options for export-import operations -> bad idea.

**Comment by vmuzikar** [comment]
Thank you all for the reports and details. I believe this has been fixed by https://github.com/keycloak/keycloak/pull/19645. Could you please give it a try?

I'm going to close this issue but if you believe it's still valid, feel free to reopen.

**Comment by johanneskastl** [comment]
I am still having this issue with 22.0.3 installed via Keycloak-operator. I'll try to disable the cache and test again.

**Comment by johanneskastl** [comment]
I am still having this issue with 22.0.3 installed via Keycloak-operator. I tried to set the cache to disabled, but the export still fails:

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
[...]
spec:
[...]
  instances: 1
  transaction:
        xaEnabled: false
```

**Comment by johanneskastl** [comment]
> I am still having this issue with 22.0.3 installed via Keycloak-operator. I tried to set the cache to disabled, but the export still fails:
> 
> ```
> apiVersion: k8s.keycloak.org/v2alpha1
> kind: Keycloak
> [...]
> spec:
> [...]
>   instances: 1
>   transaction:
>         xaEnabled: false
> ```

Seems like this did the trick:

```
  additionalOptions:                                                                                                                                                                         
    - name: cache                                                                                                                                                                            
      value: local                                                                                                                                                                           
    - name: cache-stack                                                                                                                                                                      
      value: udp
```
