### ISSUE TITLE
update or replace base64-js and js-sha256

### ISSUE THREAD

**Issue by Codem0nky** [keycloak/keycloak#15769]
### Description

update or replace base64-js and js-sha256:

Warning: /.../oss/keycloak-angular/example/node_modules/keycloak-js/dist/keycloak.mjs depends on 'base64-js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /.../oss/keycloak-angular/example/node_modules/keycloak-js/dist/keycloak.mjs depends on 'js-sha256'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

### Motivation

cause optimization bailouts

### Details

N/A

**Comment by janostik** [comment]
We're now facing the same issue. Is there any update on this?

**Comment by janostik** [comment]
We're now facing the same issue. Is there any update on this?

**Comment by Freakaz0id** [comment]
Using vite, I also get this warning, because sjs-sha256 seems to be deprecated:
```
Use of eval in "node_modules/js-sha256/src/sha256.js" is strongly discouraged as it poses security risks and may cause issues with minification.

Use of eval in "node_modules/js-sha256/src/sha256.js" is strongly discouraged as it poses security risks and may cause issues with minification.
```

**Comment by vasnakos** [comment]
Same issue with Angular 15. I tried to add            
```
  "allowedCommonJsDependencies": [
    "keycloak-js"
  ],
```
in the angular.json to suppress the warnings but with no success.

**Comment by WANZARGEN** [comment]
The same issue here...🥲 (vite)
![image](https://user-images.githubusercontent.com/26986739/234839838-0b8662c1-94ba-424d-900b-1f2611ccff3d.png)

**Comment by frolovsky** [comment]
Hi! If you got an error in console, like "caught SyntaxError: The requested module '/node_modules/base64-js/index.js?v=46b70b48' does not provide an export named 'default' (at keycloak.mjs?v=46b70b48:1:8)";
You can try 2 options:
a) add into optimizeDeps.include "keycloak-js"
b) install commonjs plugin https://www.npmjs.com/package/@originjs/vite-plugin-commonjs

**Comment by bbodine1** [comment]
> Same issue with Angular 15. I suppressed the warnings by adding
> 
> ```
>   "allowedCommonJsDependencies": [
>     "base64-js",
>     "js-sha256",
>   ],
> ```
> 
> in the angular.json.

More specifically, in the `targets -> build -> options` object

`angular.json`
example:
```json
{
  "name": "app-name",
  ....
  "targets": {
    "build": {
      "executor": "@angular-devkit/build-angular:browser",
      "outputs": ["{options.outputPath}"],
      "options": {
        ....
        "allowedCommonJsDependencies": ["flat", "base64-js", "js-sha256"],
        ....
      }
    }
  }
}
```

**Comment by combacsa** [comment]
Could this be related with https://github.com/emn178/js-sha256/issues/18 ?

**Comment by jonkoops** [comment]
Thanks for reminding me @combacsa. It does indeed look like this issue is now resolved as the new version of `js-sha256` now ships without using `eval()`. I'll go ahead and close this issue.

**Comment by prewk** [comment]
This issue is not solved, the (basically unmaintained) package js-sha256 has only removed `eval()` which removes a RollupJS warning which this issue isn't about.

**Comment by jonkoops** [comment]
@prewk You are right, I had this confused for a different issue. Reopening.

**Comment by jonkoops** [comment]
If anyone knows a good alternative to `js-sha256` and `base64-js` that is fully ESM compatible, popular and actively maintained let me know.

I am willing to entertain the idea of making a breaking change to Keycloak JS by using the Web Crypto API if it allows us to shed some dependencies. This would be a breaking change as some of our methods, as that API is async, and a lot of our public API is not.

**Comment by codespearhead** [comment]
| Current Library | Maintained Alternative |
|---|---|
| [base64-js](https://github.com/beatgammit/base64-js) | [js-base64](https://github.com/dankogai/js-base64) |
| [js-sha256](https://github.com/emn178/js-sha256) | [noble-hashes](https://github.com/paulmillr/noble-hashes) |

@robrez Will the above replacements solve the problem of the ESM-compatible builds reported in #30261 ?

**Comment by jonkoops** [comment]
We no longer need to replace `base64-js`, as this has been removed under #26265. I think `@noble/hashes` is a good replacement, it looks to be more actively maintained and audited, as well as being more popular overall. If someone wants to create a PR to use it as a replacement I'd gladly accept it.

**Comment by jonkoops** [comment]
Wanted to give a quick status update here, thanks to @schreibse we managed to replace `js-sha256` with `@noble/hashes`  (see #30667). However, I am experimenting with the Web Crypto API and I think we can drop the dependency altogether (see #33251). Feel free to try it out and let me know what you think!

If this works out well I think we'll see if we can make Keycloak JS entirely dependency free.
