### ISSUE TITLE
Condition with Property of type MULTIVALUED_STRING_TYPE is not displayed/editable after upgrade to latest version

### ISSUE THREAD

**Issue by raphisuter** [keycloak/keycloak#16640]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

We developed a condition which allows us to configure multiple networks which are excluded from login with OTP. While testing after upgrading from V15 to V20 of Keycloak we found this issue. The existing values cannot be displayed in Keycloak V20 and cannot be edited or reset.

V15:
![image](https://user-images.githubusercontent.com/7498360/214817793-68c18de4-a1f7-4f14-a8c3-64f2fc9dde9c.png)

V20:
![image](https://user-images.githubusercontent.com/7498360/214818003-efd6a638-4693-4005-916b-765d9d62cad6.png)

In Chrome DevTools it is visible that the data is present and transmitted to the UI:
![image](https://user-images.githubusercontent.com/7498360/214818778-9f336a82-a629-4532-8140-c0937e7631f3.png)

If I click clear and try to reset it again, there is an Exception thrown in the console.
![image](https://user-images.githubusercontent.com/7498360/214819484-2197e57e-2235-4c15-89a5-fc5519bf5c4d.png)

### Version

20.0.3

### Expected behavior

Property should be displayed, editable and savable as in previous versions.

### Actual behavior

Existing values are not displayed. Reseting it leads to an exception.

### How to Reproduce?

1. Create Condition with Property of type MULTIVALUED_STRING_TYPE
2. Create new Authenticaton Flow
3. Add Condition to Authentication Flow
4. Set Value of MULTIVALUED_STRING_TYPE Property
5. Save

**Comment by ssilvert** [comment]
@raphisuter I believe this is fixed via https://github.com/keycloak/keycloak-ui/issues/3743

Can you give it a try with the nightly build?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by raphisuter** [comment]
Hi @ssilvert 
I downloaded the latest nightly build and tested it locally on windows with OpenJDK (bare metal) in dev mode. The problem still exists, the values of the multivalued strings are not display correctly. What changed is that there is now a error visible in the DevTools console (see my screenshot). I also tried to clear the list and reset it, this still leads to the same error which is displayed in the screenshot of the console in the original post.
![image](https://user-images.githubusercontent.com/7498360/215030351-f9cd83b8-cb52-4881-8a83-546b30f745ab.png)
