### ISSUE TITLE
Keycloak 21.0.1 - Paging and filtering not working in "Assign roles" popup"

### ISSUE THREAD

**Issue by djotanov** [keycloak/keycloak#17403]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

In the new Admin UI, in "Role Mapping" tab for a user, when clicking on "Assign roles" button, the popup will display only the first page of role results. Clicking on next, will display the same first page of results, so its not possible to display subsequent pages.

When entering search term in "Search by role name" field, the search term doesn't affect the result, but the same unfiltered first page of results is displayed.

The requests sent to keycloak server: 
- /role-mappings/realm/available?first=**0**&max=11&search=ROLE_USER - result contains all roles (I have 50 in the realm), but the UI displays only first 10
- /role-mappings/realm/available?first=**20**&max=11&search=ROLE_USER - result contains all roles (I have 50 in the realm), but the UI displays only first 10, so the "first" and "search" parameter are not taken into account at all.

### Version

21.0.1

### Expected behavior

- Clicking on next should display next p[age instead of first page only
- Entering search term should display only matching roles

### Actual behavior

- Clicking on next shows first page only
- Entering search term has no effect on search results (non-matching roles are retrieved)

### How to Reproduce?

- Add more then 10 roles to the realm
- See that paging and filtering on "Assign roles" popup don't work

### Anything else?

This is pretty much a blocker for us for upgrading to version 21. In version 20 the issue also exists, but then at least we had an option to switch back to old admin UI. Now that the old admin UI has been removed, there is no workaround for us any more.

**Comment by Vespasian** [comment]
This is also happens when adding a user to a group.
The paging on the group modal does not work.

**Comment by ssilvert** [comment]
We have made several fixes in this area.  Can you try out the nightly build and let us know if the problem persists?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by djotanov** [comment]
Same behavior in the nightly, still broken

**Comment by stianst** [comment]
@ssilvert looks important. We should probably at least fix in Keycloak 22, but also consider backporting to 21.0?

**Comment by jbman** [comment]
The query users/<user-id>/role-mappings/realm/available?first=0&max=1 does return all available roles also on 20.0.5

**Comment by potob** [comment]
Same issue also occurs on Keycloak 20.0.5. But there's at least the possibility to switch back to the old UI.

**Comment by ssilvert** [comment]
I have also verified that this is still broken in the nightly.  Will fix ASAP.

**Comment by netdip** [comment]
Hi Team

Yes actual issue is fixed at 21.0.1 but we noticed few more issue and 21.0.1 as below.

whenever any domain/realm is imported, UI is not showing any status message like success/failure but it is imported
whenever any role is created, UI is not showing any status message like success/failure but role has been created.
Regards
Dipten

**Comment by joggeli34** [comment]
The filtering still doesn't work in version 21.0.2. When searching for something, always the same roles are shown and the pagination is not working yet. Was this somehow not properly merged to 21.0.2?

**Comment by jonkoops** [comment]
This fix was not added to a patch release due to changes in our release process. It is expected to come with 21.1.0.

**Comment by lrozenblyum** [comment]
Hello @jonkoops was it included into the Keycloak 21.1.0 release? I've set up this version and still have the same behavior on the groups screen - roles pagination doesn't work, search doesn't work.

**Comment by jonkoops** [comment]
@lrozenblyum can you test the latest changes in 21.1.1? If you are still experience problems please file a new issue.

**Comment by lrozenblyum** [comment]
@jonkoops reproduced and reported https://github.com/keycloak/keycloak/issues/19981

**Comment by jonkoops** [comment]
Thanks!
