### ISSUE TITLE
UI glitches in Users - Groups - Join Group

### ISSUE THREAD

**Issue by nblock** [keycloak/keycloak#19582]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

The following UI glitches occur when trying to manage a user's group from the "Users" &rarr; "Groups" &rarr; "Join Groups" menu:

* Pagination does not work: only the first 10 entries are shown - each click on pagination arrow shows the same entries and adds a new line for the currently selected group
* search only displays the first result, even if multiple matches are available

### Version

21.0.2

### Expected behavior

* Working pagination
* Search should show all matches (just like the search in "Groups" menu)

#### Open "Join Groups"
![image](https://user-images.githubusercontent.com/131119/230567610-af0632b7-2f46-4517-a7cc-32c4b8766d0f.png)

#### First click on pagination
* "group1" is duplicated
* results have not changed
![image](https://user-images.githubusercontent.com/131119/230567765-d46c34e0-5727-40aa-ad7d-311067ff342d.png)

#### Second click on pagination
* "group1" is duplicated
* results have not changed
![image](https://user-images.githubusercontent.com/131119/230567974-8852275f-e854-4b58-8f48-eb685c306d31.png)

### Search
25 subgroups exist within `group1`: `abc1000 - abc1025`

* Search term `102` shows only one entry
* The following entries should be displayed:
  * `abc1020`
  * `abc1021`
  * `abc1022`
  * `abc1023`
  * `abc1024`
  * `abc1025`
![image](https://user-images.githubusercontent.com/131119/230568314-d0b1d0f2-2be7-4b25-ae10-688efd15d4ef.png)

### How to Reproduce?

* Create more than 10 subgroups within a group
* Add a new user
* "Users" &rarr; "Groups" &rarr; "Join Groups"

### Anything else?

Tested with Firefox 111.0.1 and Chromium 111.0.5563.110

**Comment by nblock** [comment]
Updated area to `admin/ui`

**Comment by ssilvert** [comment]
This should be fixed in the latest nightly build.  Can you give it a try and let us know?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by nblock** [comment]
> This should be fixed in the latest nightly build. Can you give it a try and let us know?
> 
> https://github.com/keycloak/keycloak/releases/tag/nightly

Actually no, both issues are still present.

Tested https://github.com/keycloak/keycloak/releases/download/nightly/keycloak-999.0.0-SNAPSHOT.tar.gz with a sha256sum of `425502bb77b2b4f4e81e2e941813af6da82dad5561f30dc4b86442eeb0a05f83`

**Comment by ssilvert** [comment]
I see it now.  I'm attaching a file we can use with partial import to create many groups and subgroups.  The dialog is definitely messed up when you are in a subgroup.
[group-many.zip](https://github.com/keycloak/keycloak/files/11190582/group-many.zip)

**Comment by Einlanzerous** [comment]
For what it's worth, in 21.1.1 the user page works with roles, but still seeing pagination issues with groups page. Hitting next page does not load any additional entries. (Assign roles to group details)

**Comment by edewit** [comment]
@Einlanzerous think this didn't make it into 21.1.1
