### ISSUE TITLE
Stop using font icons for IdP logos

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#21548]
Currently the IdP provider logos in for the login theme are [being constructed](https://github.com/keycloak/keycloak/blob/817f129484f5904efa81959be411daea056798b6/services/src/main/java/org/keycloak/forms/login/freemarker/model/IdentityProviderBean.java#L83-L95
) from a font-based spite-sheet. This is problematic, as it loads entire sprite sheets for presenting a couple of icons. Instead, an IdP should provide an icon file that can be loaded statically.

Under this issue the following needs to happen:
- Stop loading sprite sheets for font icons for the IdPs (such as [the side-loaded PF4 icons](https://github.com/keycloak/keycloak/blob/817f129484f5904efa81959be411daea056798b6/themes/src/main/resources/theme/keycloak/common/resources/lib/pficon/pficon.css), and various [FontAwesome icon classes](https://github.com/keycloak/keycloak/blob/75741d17ab0100f36e7066e59b967b38de764c25/themes/src/main/resources/theme/keycloak/login/theme.properties)).
- Replace the aforementioned icons with proper SVG versions.
-  Deprecate [`IdentityProviderBean#getLoginIconClasses()`](https://github.com/keycloak/keycloak/blob/817f129484f5904efa81959be411daea056798b6/services/src/main/java/org/keycloak/forms/login/freemarker/model/IdentityProviderBean.java#L83-L95), and create an issue to remove this method in the next major.

**Comment by ssilvert** [comment]
Done.

**Comment by jonkoops** [comment]
This has not been completed, the code mentioned in the issue still exists.

**Comment by jonkoops** [comment]
Bumping this to the v27 milestone, since the login v1 theme depends on this functionality and that code will be around for the entire cycle of v26.
