### ISSUE TITLE
Admin URL doesn't fully honor `--hostname-url`

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#23411]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

Setting `hostname-url` doesn't set schema for admin hostname. 

For example if using Keycloak with a reverse proxy that doesn't set `X-Forwarded-Proto` that is connected to Keycloak over `http` setting `hostname-url=https://something` doesn't work for the admin console as admin URLs ends up with `http` instead of `https` even though `hostname-url` has been set, and no specifics have been set for admin.

### Version

22.0.2

### Expected behavior

Front and admin URLs should be set to `hostname-url` exactly unless `hostname-admin` or `hostname-admin-url` have been set.

### Actual behavior

Admin URLs are not set to `https`, but follow the rest of the URL schema for `hostname-url`.

### How to Reproduce?

Use https://serveo.net/ or another similar service to get a public URL for a local Keycloak deployment:
```
ssh -R 80:localhost:8080 serveo.net
```
This will output a domain name you can use to access the local Keycloak deployment publicly, including `https` and a valid certificate.

Then start Keycloak with:
```
kc.sh start-dev --hostname-url=https://xxxxx.serveo.net --hostname-debug=true
```

Replace `xxxxx` with output from the previous `ssh` command.

Now open https://xxxxx.serveo.net/realms/master/hostname-debug and observe Frontend URLs are set correctly, but Admin URL is using `http` instead of `https`.

**Comment by mabartos** [comment]
@stianst @vmuzikar I'm not sure about the validity of this issue, at least for Keycloak 22.x . AFAIK, it was intentional to rather rely on parsing incoming request headers than using the frontend URL when the hostname admin props are not set. At least this info is present in the documentation[1]. The reasoning behind it is valid as we allow access to the console through a public domain or private network by default. In order to override the behavior, the admin props should be overridden.

We could potentially change the default behavior for the next releases, but I'm afraid we are not able to do it for Keycloak 22.x as it'd mean a breaking change in the behavior.

The issue you're facing in the hostname debug tool is more related to the used HTTPS tunnels or SSH reverse tunnels such as `serveo`, or `ngrok`. AFAIK, they're terminating TLS, and HTTP is used when sending requests through the tunnels. I've also verified it in Wireshark as the full request URI uses HTTP when I access the URL provided by `serveo`.

The hostname should work properly and the hostname debug tool as well, when I use a custom hostname with mapped `/etc/hosts`, like in `HostnameDistTest`.

I think we could only improve test coverage for such cases with the settings of the admin props.

The proper functionality should be verified in #23535.

Removing milestone `22.0.4` and adding `triage` label to discuss it. However, we are about to change the behavior of the hostname as a whole, so it might not be relevant later anymore. 
 
[1] https://github.com/keycloak/keycloak/blob/main/docs/guides/server/hostname.adoc#administration-console

**Comment by mabartos** [comment]
It's rather an RFE than a bug as we expect such a behavior.

**Comment by vmuzikar** [comment]
Actually, this IS a bug. If `hostname-url` is set and `hostname-admin-url` NOT set, the admin console is supposed to use the `hostname-url` values. This is aligned with `hostname` and `hostname-admin` options. We should fix it (regardless of how our wider effort for resolving hostname issues will progress).

**Comment by mabartos** [comment]
@vmuzikar Still not convinced about the validity for Keycloak 22.x. It'd cause a breaking change as stated in the docs[1]:
```
By default, the URLs for the administration console are also based on the incoming request.
```
If we rely on the `hostname-url` when the `hostname-admin-url` is NOT set, users will face different behavior as it will NOT allow client-server communication through a private network, same as for the Backend[2]. At least the information is included in the docs. 

[1] https://github.com/keycloak/keycloak/blob/main/docs/guides/server/hostname.adoc#administration-console
[2] https://github.com/keycloak/keycloak/blob/main/docs/guides/server/hostname.adoc#backend

**Comment by vmuzikar** [comment]
Sounds like we have a bug in docs too then. :D But I agree, the fix is basically a breaking change and we should fix it in 23.

@stianst Does it work for you too?

**Comment by mabartos** [comment]
@vmuzikar I've made a deeper analysis of the issue, even with some historical considerations and I can confirm it's actually a bug as you mentioned. In the codebase, there's some sort of inconsistency with the behavior mentioned in docs and CLI option description. 

The Admin URL should really honor the `--hostname-url` property.

I'll prepare a fix for it.

**Comment by vmuzikar** [comment]
This will be resolved as part of https://github.com/keycloak/keycloak/issues/24252. Keeping this open but removing the milestone.

**Comment by mabartos** [comment]
@vmuzikar I'm assigning the issue to you as you're the assignee for #24252, which is strongly related. Is it ok?

**Comment by ckaspro** [comment]
Not sure whether to amend this here or open a new bug, but I see the connection. I also do have the admin-url set (KC23.0.5), and experienced several issues.
Hence I fear this is actually not only an issue in the GUI, but also the .well-known endpoint:

- e.g. viewing an Identity provider will show in the redirect URL the admin- host. As this is not reachable, this throws an error when using. Surely (or luckily?), using the normal URL is working

- viewing the endpoint config ( .well-known/openid-configuration ) will show the admin- hostnames in various URLs - also in something always used like jwks-url

Please correct me, but there is an urgent fix required...?

**Comment by mabartos** [comment]
@vmuzikar Any progress on this?

**Comment by vmuzikar** [comment]
@mabartos We'll mark it as resolved once #24252 is closed.

**Comment by vmuzikar** [comment]
This issue has been created against Hostname v1 implementation. Due to its complexities and high maintenance costs we decided to rewrite it from scratch as Hostname v2 which will be part of Keycloak 25 and will be replacing v1. For more context please see #24252.

We believe this issue has been resolved with Hostname v2. We encourage you to give it a try even before Keycloak 25 is released and report back any issues you run into. You can use the [nightly builds](https://github.com/keycloak/keycloak/releases/tag/nightly) for it. See also the [migration notes](https://github.com/keycloak/keycloak/blob/main/docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc#new-hostname-options) and [new docs](https://github.com/keycloak/keycloak/blob/e7dd5c1991e938ad2aa03e9c8b18cac6820dc7df/docs/guides/server/hostname.adoc).
