### ISSUE TITLE
Account v3 theme - Localization not working on account console

### ISSUE THREAD

**Issue by Slashchop** [keycloak/keycloak#23699]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

Using account v3 theme localization at account client is not working.  Tried different locales but the page is not translated as account v2.

This is without any localization message bundles.

Tested on 22.0.1,22.03,nightly using docker.

![1](https://github.com/keycloak/keycloak/assets/19476086/8f639f76-aa3d-4e60-86f4-bbbb398ad522)

### Version

22.0.1,22.03,nightly

### Expected behavior

Translate depending on locale all fields including menu items as it is done in theme account v2.

### Actual behavior

Nothing is translated except "Account Console" in Applications tab.

![2](https://github.com/keycloak/keycloak/assets/19476086/92f880fb-ff62-45ac-ac2a-80132a282247)

### How to Reproduce?

Default installation using --features="account3" or --features="preview" . 
Create a new realm, change Account theme theme to "keycloak.v3" and enable Localization with locale(s). 
Login to client account with a user.

### Anything else?

Thank you for your time.

**Comment by ssilvert** [comment]
I have recreated this.  There is a lot that is not translated in V2.  But I'm not seeing anything translated in V3.

**Comment by edewit** [comment]
I'll assign this to @jonkoops as he did the overrides in admin ui and this in account

**Comment by teunis90** [comment]
I can confirm this issue on Keycloak release 23.

**Comment by jonkoops** [comment]
I need to work on some other things, so I don't have time to get to this for a while. If anyone else wants to take this go right ahead.

**Comment by ssilvert** [comment]
This should be fixed now.

**Comment by cljk** [comment]
I think this is NOT fixed?!

I´m on 26.3.4 and started digging how I can translate the account-console to `de` - just to see that there is already a translation in the source repository - but is not displayed.

The locale is `de` but the application is displayed in `en`.

<img width="1213" height="704" alt="Image" src="https://github.com/user-attachments/assets/d3882570-b6a2-4dda-a098-b9de00e3131e" />

**Comment by edewit** [comment]
After I save my settings the site is translated:

<img width="2242" height="1057" alt="Image" src="https://github.com/user-attachments/assets/57b0d7d3-8bda-4db7-b397-ce31c7f0433a" />
