### ISSUE TITLE
Admin UI User Profile attribute labels are not translated with the settings under Realm Settings -> Localization

### ISSUE THREAD

**Issue by antikalk** [keycloak/keycloak#24472]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

In the Admin UI User Create/Update Screens User Profile Attribute Label Translation are not considering the settings done under Realm Settings -> Localization of the realm. I would have expected that this is the place where I configure the localizations.

E.g. for these localizations: 
![image](https://github.com/keycloak/keycloak/assets/1793007/0aa5f97f-3278-438f-8eae-eb336a2613b8)

The Admin UI displays the User Profile Attributes in the Create/Update User Screens as such: 
![image](https://github.com/keycloak/keycloak/assets/1793007/9f2387d5-0930-4792-8db0-19cd6472ea2f)

Whereas the Registration (Login Theme) does use the correct translated values:
![image](https://github.com/keycloak/keycloak/assets/1793007/894d43d7-3f6a-4bf6-8c5f-37a32a32b189)

My simple user profile configuration: 
```json
{
  "attributes": [
    {
      "name": "username",
      "displayName": "${username}",
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "validations": {
        "length": {
          "min": 3,
          "max": 255
        },
        "username-prohibited-characters": {},
        "up-username-not-idn-homograph": {}
      }
    },
    {
      "name": "email",
      "displayName": "${email}",
      "required": {
        "roles": [
          "user"
        ]
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "validations": {
        "email": {},
        "length": {
          "max": 255
        }
      }
    },
    {
      "name": "firstName",
      "displayName": "${firstName}",
      "required": {
        "roles": [
          "user"
        ]
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "validations": {
        "length": {
          "max": 255
        },
        "person-name-prohibited-characters": {}
      }
    },
    {
      "name": "lastName",
      "displayName": "${lastName}",
      "required": {
        "roles": [
          "user"
        ]
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "validations": {
        "length": {
          "max": 255
        },
        "person-name-prohibited-characters": {}
      }
    },
    {
      "name": "custom_attribute",
      "displayName": "${custom_attribute}",
      "permissions": {
        "edit": [
          "admin",
          "user"
        ],
        "view": [
          "admin",
          "user"
        ]
      },
      "annotations": {},
      "validations": {},
      "group": "custom_attributes_group"
    }
  ],
  "groups": [
    {
      "annotations": {},
      "displayDescription": "${custom_attributes_group_description}",
      "displayHeader": "${custom_attributes_group}",
      "name": "custom_attributes_group"
    }
  ]
}
```

### Version

main

### Expected behavior

Admin UI User Profile attribute labels are translated with the settings under Realm Settings -> Localization

### Actual behavior

Admin UI User Profile attribute labels are not translated with the settings under Realm Settings -> Localization

### How to Reproduce?

1. Create a realm with user profile enabled
2. Create a custom user profile attribute with a displayname using localization, e.g. `${custom_attribute}`. Make it view and editable for all.
3. Enable localization and provide a translation for the key `custom_attribute`
4. Enable user registration
5. Go to the Login -> Registration page: See the attribute label being translated
6. Go to the Admin UI -> Create user page: See the attribute label not being translated

**Comment by ssilvert** [comment]
@antikalk I think this may be a setup issue.  Please take a look at my example for how to do this here:
https://github.com/keycloak/keycloak/issues/19611#issuecomment-1568980050

**Comment by ssilvert** [comment]
@antikalk Oh, never mind.  From your JSON it looks like your setup is correct.

**Comment by edewit** [comment]
fixed with https://github.com/keycloak/keycloak/pull/24445

**Comment by antikalk** [comment]
@edewit I don't think this issue is closed with PR #24445. That PR only enabled the Group Name and Group Description to go through the frontend translation functions at all. Still the localizations configured in the realm settings might not apply in the admin UI but only in the login theme. In the screenshots I provided in this issue, I accidentally was on the branch that has been merged - hence why the translation key is displayed also for group labels. I will try to verify this with the next nightly.

**Comment by antikalk** [comment]
I can confirm that this issue still exists in the nightly, but only when accessing the screens with the master realm admin console:

![image](https://github.com/keycloak/keycloak/assets/1793007/f7318da7-11a6-4cbe-afe8-0cab6407df63)
With the master admin console:
![image](https://github.com/keycloak/keycloak/assets/1793007/8c55bede-3322-4fc4-a172-1f89f2365faf)
With the test realm admin console:
![image](https://github.com/keycloak/keycloak/assets/1793007/86b6c657-d446-40f1-beff-5b65b5379f9c)
And the login theme:
![image](https://github.com/keycloak/keycloak/assets/1793007/ac9feba7-af51-4ba4-a229-24cdeeefa39a)

So I think this story can stay closed in favor of https://github.com/keycloak/keycloak/issues/22431
