### ISSUE TITLE
`update-email` preview feature and "Update Profile" required user action lead to losing email data

### ISSUE THREAD

**Issue by gjherbiet** [keycloak/keycloak#24955]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

Enabling `update-email` preview feature and having users going through the the "Update Account Information" screen (by setting "Update Profile" in "Required user actions") lead to the "Email" data being deleted from the user account data when this login screen is submitted.

This might be caused by the "Update Account Information" screen not displaying the "Email" field when `update-email` preview feature is enabled.

"Update Account Information" with `update-email` preview feature enabled:
<img width="527" alt="Update Account Information with update-email enabled" src="https://github.com/keycloak/keycloak/assets/210227/290258d1-c668-47e1-b6b5-82ee232d0f09">

"Update Account Information" with `update-email` preview feature disabled:
<img width="530" alt="Update Account Information without update-email enabled" src="https://github.com/keycloak/keycloak/assets/210227/41ed5a00-f635-47e3-8546-d9fe278bb7dc">

### Version

22.0.5

### Expected behavior

1. "Update Account Information" screen displays the email field when `update-email` preview feature is enabled.
2. User "Email" data is kept after "Update Account Information" screen is submitted when `update-email` preview feature is enabled.

### Actual behavior

1. "Update Account Information" screen does not display the email field when `update-email` preview feature is enabled.
2. User "Email" data is deleted after "Update Account Information" screen is submitted when `update-email` preview feature is enabled.

### How to Reproduce?

1. Enable `update-email` preview feature.
1. Create (or update) a user account with "Update Profile" in required user actions.
1. Log in using the created (or updated) user account.
1. Note the "Update Account Information" login screen does not show the "Email" field.
1. After clicking on "Submit" on this screen, the "Email" field in the user account is empty.

**Comment by jonkoops** [comment]
ping @pedroigor

**Comment by mposolda** [comment]
Adding to milestone 26 for now. We will take a look when we're going to work on promote "Update email" feature to be supported.

In the meantime, anyone is welcome to investigate this and possibly send PR for this to latest Keycloak main. One note is, that this might be already fixed in the latest Keycloak nightly release and hence would be fixed in Keycloak 24. If anyone can confirm this is already resolved, it can be nice as this would be useful info as well.

**Comment by reda-alaoui** [comment]
I just tested this on master (8d3d94f904cd005e77840263f2616cfa2df29429). 
I cannot reproduce the issue using the provided steps. 

In my tests, the email is not lost.

**Comment by graziang** [comment]
I also tested it on main and I cannot reproduce the issue, the email is not lost.

**Comment by pedroigor** [comment]
Thanks @graziang. I also confirm it is no longer an issue. Should be fixed at least in Keycloak 24.

**Comment by RuchiSingh18** [comment]
Still facing issue with Update Account information when first login attempt with keykloak 24.0.5. its not working as expected. please check

**Comment by jonkoops** [comment]
> Still facing issue with keycloak 24.0.5

That version of Keycloak is no longer supported, try using the latest version of Keycloak (26.0.0 at time of writing) and see if the problem occurs there. If it still does, then please report a new issue.
