### ISSUE TITLE
Un-friendly error message for Fail Import option in keycloak GUI

### ISSUE THREAD

**Issue by pravsjv** [keycloak/keycloak#28017]
### Description

Need improvement in error message in the attached screen.

Step1:
Go to Realm settings -> click Action -> choose Partial export -> change Include groups and roles, Include clients to On -> click Export button -> realm json file is generated -> OK

![Screen Shot 2024-03-18 at 12 24 07 PM](https://github.com/keycloak/keycloak/assets/20001725/e5193d51-c5c2-49b5-9ba2-b3b4339a7001)

Step 2. 
Go to Realm settings -> click Action -> choose Partial import -> click Browse button -> choose realm json file is generated in the step 1 -> Choose all the resources you want to import

Step3: 
If pick ‘If a resource already exists, specify what should be done’ field = “Fail import” value -> click Import button

 Actual : Display error message as below: ‘ Import failed: HTTP 500 Internal Server Error’
 
![Screen Shot 2024-03-18 at 12 24 52 PM](https://github.com/keycloak/keycloak/assets/20001725/61effda7-ea03-4475-8bba-32745fc57868)

### Motivation

Better excpetion/alert message gives us more clarity of what the issue instead of a generic message.

**Comment by jonkoops** [comment]
@pravsjv just to confirm, what is the Keycloak version this is happening in?

**Comment by pravsjv** [comment]
@jonkoops Keycloak 21.1.2

**Comment by jonkoops** [comment]
We no longer support that version, could you try on the latest Keycloak version and see if it works. This might be a but that is already fixed.

**Comment by keshav-deshpande-intension** [comment]
@jonkoops Hello, I could reproduce this issue on the keycloak 25.0.2. The error is still generic with HTTP 500.

**Comment by Dunedubby** [comment]
Any update here?

**Comment by jonkoops** [comment]
I can reproduce this on the latest version of 25 and on the `main` branch. I'll mark this issue as triaged.

**Comment by keshavprashantdeshpande** [comment]
@jonkoops I would like to work on this issue. Can you please assign the issue to me? After that I will write a short summary of what I will exactly change.

**Comment by jonkoops** [comment]
Sure, feel free to submit your proposal in the form of a pull request if you are confident about what the fix should be.
