### ISSUE TITLE
User profile validation pattern error-message not rendered from messages_en.properties

### ISSUE THREAD

**Issue by DaBonse** [keycloak/keycloak#29098]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I use translation placeholder to configure messages for the user profile attributes. This worked as expected.

The translations located in the propertie file of the admin theme.

But the error-message for the pattern validator will not be rendered. Other placeholder translations like annotations work fine in the same properties file, e.g. `profile.attribute.myAttribute.placeholder` and `profile.attribute.myAttribute.description`.

I tested it with "Add User" in the Admin UI keycloak.v2 theme.

**Part of json config of the user profile:**

`{
  "name": "myAttribute",
  "displayName": "${profile.attribute.myAttribute}",
  "validations": {
    "pattern": {
      "pattern": "^(admin|abc[0-9]{9,9})$",
      "error-message": "${profile.attribute.myAttribute.validator.errorMessage}"
    }
  },
  "annotations": {
    "inputTypePlaceholder": "${profile.attribute.myAttribute.placeholder}",
    "inputHelperTextBefore": "${profile.attribute.myAttribute.description}"
  },
  "required": {
    "roles": [
      "admin",
      "user"
    ]
  }`

**Content in: admin/messages/messages_en.properties**

`profile.attribute.myAttribute.validator.errorMessage=My error message`

### Version

nightly Docker build

### Regression

- [ ] The issue is a regression

### Expected behavior

Validator message should be rendered like other placeholders.

### Actual behavior

see description on top

### How to Reproduce?

- create a new realm
- configure user attribute like my example
- expand keycloak.v2 admin theme only with the admin/messages/messages_en.properties file
- activate the custom theme
- create a new user over Admin UI in the realm and put a invalid value to the attribute form field

**Comment by edewit** [comment]
fixed it and btw you can use the regex in your message like this:
```
profile.attribute.myAttribute.validator.errorMessage=My error message it must adhere to regex: {{1}}
```

**Comment by DaBonse** [comment]
In Version 25.0.1 it still not working. The nightly build is not testable at this time, because user profile ui is broken.

I am waiting for merging and will test it again.

**Comment by DaBonse** [comment]
In Keycloak 26.0.7 the bug is still present.


And now, the rendering of displayName and annotations inputTypePlaceholder is also broken.


**In the admin UI:**

![image](https://github.com/user-attachments/assets/c09538b9-511d-4f9d-b919-ffbd49ce192c)

**In messages_en.properties:**

![image](https://github.com/user-attachments/assets/b1c09fcb-2ee4-41c1-bbc9-6dee8be1c2ea)

**Comment by DaBonse** [comment]
I don't know why, but now it is working, maybe a cache thing. Anyway, now it works fine in the Admin UI.
