### ISSUE TITLE
local user login not possible after LDAP connection problem

### ISSUE THREAD

**Issue by go-ma123** [keycloak/keycloak#29147]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

Hi team,

we have configured keycloak version 24.0.3 with a ldap user federation. In addition, we have a local user with admin right for the realm as a fallback. When there are problems with the ldap connection, e.g., ldap binding credentials changes on ldap side, it is not possible to log in to the realm. Even with the local admin user.

### Version

24.0.3

### Regression

- [X] The issue is a regression

### Expected behavior

Administrator account stored in the local Keycloak user database can be used in case of problems connecting to your LDAP.

### Actual behavior

Administrator account stored in the local Keycloak user database can not log in case of problems connecting to your LDAP.

### How to Reproduce?

1. setup realm
2. create admin account in local keycloak database
3. configure a valid LDAP connection
4. Interrupt LDAP connection (e.g. changing the binding credentials or changing the ldap url)
5. log in with local admin account  -> log in error

### Anything else?

![keycloak-admin-login-ldap-broken](https://github.com/keycloak/keycloak/assets/168421208/b32abd8a-efc1-4992-9636-3bef421fce59)

**Comment by martin-kanis** [comment]
@go-ma123 Thanks for reporting of the issue. This is similar as https://github.com/keycloak/keycloak/issues/23913, https://github.com/keycloak/keycloak/issues/25129 issues that we decided to close. I agree that the usecase you describe make sense to fix, and local Keycloak admin should be allowed to be logged into the admin console in order to fix connection to the LDAP server. 
Nevertheless, this issue is not a regression and was present in older Keycloak releases.

**Comment by go-ma123** [comment]
@martin-kanis : we create the user before we configured LDAP. To log in with a local account when ldap had connection issues worked fine with 23.0.7 and earlier. That's why it is a regression in my opinion.

**Comment by martin-kanis** [comment]
Hmm OK, then it indeed seems to be little bit different and worse issue. Thanks for additional info.

**Comment by sguilhen** [comment]
This was fixed by https://github.com/keycloak/keycloak/pull/29134 which was merged yesterday. The fix will be backported to Keycloak 24 branch.

**Comment by sguilhen** [comment]
Backport PR that also fixes this issue: https://github.com/keycloak/keycloak/pull/29219

**Comment by vsudebil** [comment]
The issue persists in the current version of Keycloak.

When LDAP is unreachable and a local (non-LDAP) user tries to log in, Keycloak still attempts to query the LDAP provider if the user’s username and email differ.

From debugging, the flow first calls getUserByEmail() before falling back to getUserByUsername(). If the user’s email doesn’t match any local record (or if the realm is configured to allow email login), Keycloak tries to search LDAP, triggering:

org.keycloak.models.ModelException: Failed to fetch results from the LDAP [provider] ...
at org.keycloak.storage.ldap.LDAPStorageProvider.queryByEmail(...)


This means that even for purely local users, a broken LDAP connection still blocks login — because the system performs an LDAP lookup by email before checking the username.

Expected behaviour: if a local user exists in the internal store, Keycloak should not attempt any LDAP query, regardless of email lookup.

**Comment by martin-kanis** [comment]
@vsudebil Which version? We have now https://github.com/keycloak/keycloak/pull/42478 in that is supposed to fix the problem.

**Comment by vsudebil** [comment]
@martin-kanis 
I just tested this in version 26.4.1 (to be sure), and the problem is still there.

Steps to reproduce:

1. Configure a user federation with a read-only/unsynced LDAP provider.
2. In realm settings, set "Login with email" to On.
3. Create a local user whose username contains an “@” character.
4. Block communication to the LDAP server.
5. Attempt to log in with the created user (the one with “@” in the username).

Observed behaviour:
Keycloak attempts to log in by email, querying the LDAP provider and failing — it never reaches the loginByUsername step.


```
at org.keycloak.storage.UserStorageManager.tryResolveFederatedUser(UserStorageManager.java:1142)
        at org.keycloak.storage.UserStorageManager.getUserByAttribute(UserStorageManager.java:1137)
        at org.keycloak.storage.UserStorageManager.getUserByEmail(UserStorageManager.java:541)
        at org.keycloak.models.cache.infinispan.UserCacheSession.getUserByEmail(UserCacheSession.java:438)
        at org.keycloak.models.utils.KeycloakModelUtils.findUserByNameOrEmail(KeycloakModelUtils.java:321)
       at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.getUserFromForm(AbstractUsernameFormAuthenticator.java:168
```

**Comment by martin-kanis** [comment]
@vsudebil Can you please create a new issue for this?
