### ISSUE TITLE
Searching for users in a LDAP-backed realm removes the focus from the search-bar after the first letter

### ISSUE THREAD

**Issue by Anderen2** [keycloak/keycloak#29153]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When using the search-box, the first letter entered seems to trigger something that removes the text about "This realm may have a federated provider". 
![image](https://github.com/keycloak/keycloak/assets/2698648/2bfd51b4-0746-44d5-bd34-af302ec792c2)

However, by doing so, it also removes the focused element, causing the next key-inputs to be /dev/null'd, until you re-press the search-bar again. 

![image](https://github.com/keycloak/keycloak/assets/2698648/0c50ad90-8c1f-458d-a696-95b68829b7ee)

### Version

24.0.3.redhat-00004

### Regression

- [X] The issue is a regression

### Expected behavior

Focus when typing in the search-bar is not removed after the first letter. 

### Actual behavior

When you type in the search bar, the focus is removed after the first character. You then need to click back into the searchbar again. 

### How to Reproduce?

Might be linked to the message regarding "This realm may have a federated provider". This only occurs in those realms. For non-federated realms it seems like this is not an issue.

**Comment by edewit** [comment]
~old-release
This has been fixed already

**Comment by vbrik** [comment]
> ~old-release
> 
> This has been fixed already

Still a problem in 24.0.3

**Comment by denis-volin** [comment]
> ~old-release
> 
> This has been fixed already

In which release?

**Comment by ssilvert** [comment]
@denis-volin I can see that it is fixed in the nightly build.  So it will at least be in the next release.  I'm going to close this issue.

**Comment by bjoernhype** [comment]
Today 24.0.5 was released, and the bug still exists. Who can check?
