### ISSUE TITLE
Keycloak admin console interface is out of screen 

### ISSUE THREAD

**Issue by i62pecar** [keycloak/keycloak#32758]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Hello, I'm currently using Keycloak 25.0.1 and I have a problem with the user interface.

![image](https://github.com/user-attachments/assets/96a51e1e-2687-4edf-acc6-b9ed1cf9e816)

As you can see the name of the resources is too long, so the options for the resources are missing.
To be able to see the options I need to zoom out a lot, so the text is small and barely readable.

![image](https://github.com/user-attachments/assets/cae51e9f-d74b-4fb8-acaa-cceec8a96094)

Would it be possible to add a scroll bar in this screen so we can scroll left and right without zooming the content?

Or maybe if the resources are too long show them like "Reso...urce".

Just throwing some ideas of how this can be fixed. Thanks for your time! :)

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

It would be nice to have a scroll bar on the bottom so we can slide through the resource or maybe shorten the names of the resources so it all can fit in the screen.

### Actual behavior

Resource options move out of screen.

### How to Reproduce?

Create resources with a large name (e.g. did:key:z2dmzD81cgPx8Vki7JbuuMmFYrWPgYoytykUZ3eyqht1j9KbndPZwZdDNWhmLXsumWsx3QjsyPUaom15cgySHS2K27aSdrqBzZ9kSJHWKkDiQQ26gc7zCDVfvrzyuumtFNUBDMPEBqeodyAM6krZSvNDo7zWvt319Lxhd9dTEKMAAfLgbN)

**Comment by edewit** [comment]
This has been fixed
~old-release

**Comment by i62pecar** [comment]
> This has been fixed ~old-release

I've tried latest release (25.0.5) and the error still occurs, in what version is this fixed? 

Thank you.

**Comment by edewit** [comment]
on main

**Comment by davux** [comment]
@edewit, what future release of Keycloak (major, minor or patch) will contain that fix?

**Comment by ssilvert** [comment]
@davux It will definitely be fixed in Keycloak 26.  If you search the issues you can probably find the issue that fixed it and see if it has a label for being fixed in a minor release as well.

**Comment by jonkoops** [comment]
If the PR that fixes this issue is found we can backport it to v25 for you.
