### ISSUE TITLE
Clustering IT instability

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#35341]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

From running `Clustering IT` 100 times on two separate occasions there are some random failures happening in different tests.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Tests pass on each run

### Actual behavior

Tests fail randomly

### How to Reproduce?

Run `Clustering IT` job only, with retries disabled.

### Anything else?

Out of 100 runs 3 runs failed, with 2 failing tests in each run:

```
12045136616:Clustering IT	Run cluster tests	2024-11-27T07:38:43.9589692Z -- [ERROR]   UserInvalidationClusterTest>AbstractInvalidationClusterTest.crudWithFailover:47->AbstractInvalidationClusterTest.crud:55->AbstractInvalidationClusterTest.createEntityOnCurrentFailNode:109->createEntity:19->createEntity:50 » WebApplication Create method returned status Forbidden (Code: 403); expected status: Created (201). Response body: {"error":"HTTP 403 Forbidden"}
12045136616:Clustering IT	Run cluster tests	2024-11-27T07:38:43.9594150Z -- [ERROR]   UserInvalidationClusterTest>AbstractInvalidationClusterTest.crudWithoutFailover:42->AbstractInvalidationClusterTest.crud:63->AbstractInvalidationClusterTest.assertEntityOnSurvivorNodesEqualsTo:150->readEntity:19->readEntity:60 » Forbidden HTTP 403 Forbidden
12045141013:Clustering IT	Run cluster tests	2024-11-27T08:21:25.8586716Z -- [ERROR]   RoleInvalidationClusterTest>AbstractInvalidationClusterTest.crudWithoutFailover:42->AbstractInvalidationClusterTest.crud:72->testEntityUpdates:50->testEntityUpdates:151->AbstractInvalidationClusterTest.verifyEntityUpdateDuringFailover:138->assertEntityOnSurvivorNodesEqualsTo:50->assertEntityOnSurvivorNodesEqualsTo:164->AbstractInvalidationClusterTest.assertEntityOnSurvivorNodesEqualsTo:166
12045141013:Clustering IT	Run cluster tests	2024-11-27T08:21:25.8592722Z -- [ERROR]   RoleInvalidationClusterTest>AbstractInvalidationClusterTest.crudWithFailover:47->AbstractInvalidationClusterTest.crud:51->createTestEntityRepresentation:50->createTestEntityRepresentation:59->AbstractInvalidationClusterTest.createEntityOnCurrentFailNode:109->createEntity:50->createEntity:98 » Forbidden HTTP 403 Forbidden
12045141074:Clustering IT	Run cluster tests	2024-11-27T08:32:26.1491577Z -- [ERROR]   UserInvalidationClusterTest>AbstractInvalidationClusterTest.crudWithFailover:47->AbstractInvalidationClusterTest.crud:55->AbstractInvalidationClusterTest.createEntityOnCurrentFailNode:109->createEntity:19->createEntity:50 » WebApplication Create method returned status Forbidden (Code: 403); expected status: Created (201). Response body: {"error":"HTTP 403 Forbidden"}
12045141074:Clustering IT	Run cluster tests	2024-11-27T08:32:26.1496315Z -- [ERROR]   UserInvalidationClusterTest>AbstractInvalidationClusterTest.crudWithoutFailover:42->AbstractInvalidationClusterTest.crud:63->AbstractInvalidationClusterTest.assertEntityOnSurvivorNodesEqualsTo:150->readEntity:19->readEntity:60 » Forbidden HTTP 403 Forbidden
```

The first part of the line is the workflow run-id. You can find the logs at `https://github.com/stianst/keycloak/actions/runs/<run-id>` (for example https://github.com/stianst/keycloak/actions/runs/12045141013).

**Comment by stianst** [comment]
On third attempt Clustering IT failed 2 out of 100 times.

Failures include:

RealmInvalidationClusterTest#crudWithFailover
RealmInvalidationClusterTest#crudWithoutFailover
ClientScopeInvalidationClusterTest#crudWithoutFailover
ComponentInvalidationClusterTest#crudWithoutFailover

See https://github.com/stianst/keycloak/actions/runs/12237128141/job/34132372366 and https://github.com/stianst/keycloak/actions/runs/12233860447/job/34122227931

**Comment by stianst** [comment]
Did another run on 11th December:

|Job|Failing test|Failures|Jobs|
|---|------------|--------|----|
|Clustering IT|cluster.PermissionTicketInvalidationClusterTest.crudWithFailover|1|[12278248288](https://github.com/stianst/keycloak/actions/runs/12278248288)|
|Clustering IT|cluster.RealmInvalidationClusterTest.crudWithFailover|2|[12278263303](https://github.com/stianst/keycloak/actions/runs/12278263303) [12278248288](https://github.com/stianst/keycloak/actions/runs/12278248288)|
|Clustering IT|cluster.RealmInvalidationClusterTest.crudWithoutFailover|2|[12278263303](https://github.com/stianst/keycloak/actions/runs/12278263303) [12278248288](https://github.com/stianst/keycloak/actions/runs/12278248288)|
|Clustering IT|cluster.PermissionTicketInvalidationClusterTest.crudWithoutFailover|1|[12278248288](https://github.com/stianst/keycloak/actions/runs/12278248288)|
|Clustering IT|cluster.ComponentInvalidationClusterTest.crudWithFailover|1|[12278250634](https://github.com/stianst/keycloak/actions/runs/12278250634)|
|Clustering IT|cluster.GroupInvalidationClusterTest.crudWithoutFailover|1|[12278250634](https://github.com/stianst/keycloak/actions/runs/12278250634)|
|Clustering IT|cluster.ComponentInvalidationClusterTest.testComponentUpdating|1|[12278250634](https://github.com/stianst/keycloak/actions/runs/12278250634)|
|Clustering IT|cluster.ComponentInvalidationClusterTest.crudWithoutFailover|1|[12278250634](https://github.com/stianst/keycloak/actions/runs/12278250634)|

**Comment by stianst** [comment]
From 7th January runs:

|Job|Failing test|Failures|Jobs|
|---|------------|--------|----|
|Clustering IT|cluster.UserFederationInvalidationClusterTest.crudWithFailover|1|[12648664811](https://github.com/stianst/keycloak/actions/runs/12648664811)|
|Clustering IT|cluster.UserFederationInvalidationClusterTest.crudWithoutFailover|1|[12648664811](https://github.com/stianst/keycloak/actions/runs/12648664811)|
|Clustering IT|cluster.SessionFailoverClusterTest.sessionFailover|1|[12648664811](https://github.com/stianst/keycloak/actions/runs/12648664811)|
|Clustering IT|cluster.UserInvalidationClusterTest.crudWithoutFailover|1|[12648664811](https://github.com/stianst/keycloak/actions/runs/12648664811)|

**Comment by douglaspalmer** [comment]
@stianst are you still seeing these failures? I've run UserInvalidationClusterTest over 1000 times locally and with GHA, with Postgres and with mysql, I've also run the full cluster suite over 100 times locally and with GHA, with Postgres and mysql. I haven't managed to get 1 failure. Are you using a different environment?

**Comment by douglaspalmer** [comment]
@stianst given that the failures are the same and they're all permission denied; is it possible that we aren't waiting long enough for the cluster setup? Maybe a longer wait would fix the issue: https://github.com/keycloak/keycloak/blob/b8417883430ec56048dd96b27001c5c42968f010/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cluster/AbstractClusterTest.java#L187

**Comment by douglaspalmer** [comment]
FWIW, reducing the pause to 1 millisecond allows me to reproduce the failures, increasing it should hopefully eliminate them.

**Comment by stianst** [comment]
I've run 100 times on GA, and I've done that a few times. Every time I've had a few failures out of the 100.

I've disabled Surefire retries though; without that I imagine a run will never fail:

https://github.com/stianst/keycloak/blob/main/.github/workflows/stability-clustering.yml

We can try out increasing the pause for sure and see if that sorts it out (would obviously be better that it checked the cluster was up again instead of just waiting a given amount of time, but not sure how we could do that).

I can do 100 times with `pause(3000)`, and do another with `pause(5000)` and see if that eliminates the problem.

**Comment by stianst** [comment]
First run: https://github.com/stianst/keycloak/actions/workflows/stability-clustering.yml

btw I have the GitHub pro plan so can run this a bit faster since I get twice as many concurrent jobs (40 vs 20).

**Comment by douglaspalmer** [comment]
@stianst I think this code, instead of pause(6000), would completely solve the issue:

`        RemoteContainer container = (RemoteContainer)suiteContext.getAuthServerBackendsInfo().get(0).getArquillianContainer().getDeployableContainer();
        String pattern = "(?s).*Keycloak.*started.*";
        String remoteLog = container.getRemoteLog();
        while(!remoteLog.matches(pattern)) {
            pause(1000);
            remoteLog = container.getRemoteLog();
        }
        container = (RemoteContainer)suiteContext.getAuthServerBackendsInfo().get(1).getArquillianContainer().getDeployableContainer();
        remoteLog = container.getRemoteLog();
        while(!remoteLog.matches(pattern)) {
            pause(1000);
            remoteLog = container.getRemoteLog();
        }
`

**Comment by douglaspalmer** [comment]
@stianst I've updated the PR with a better fix.

**Comment by stianst** [comment]
Afraid this didn't fix the issue; had another two failed jobs with the fix:

### org.keycloak.testsuite.cluster.ClientScopeInvalidationClusterTest#crudWithoutFailover
|Run|Job|Step|
|------------|--------|----|
|[13048816319](https://github.com/stianst/keycloak/actions/runs/13048816319)|Clustering IT|cluster tests|

### org.keycloak.testsuite.cluster.ClientScopeInvalidationClusterTest#crudWithFailover
|Run|Job|Step|
|------------|--------|----|
|[13048816319](https://github.com/stianst/keycloak/actions/runs/13048816319)|Clustering IT|cluster tests|

### org.keycloak.testsuite.cluster.ComponentInvalidationClusterTest#testComponentUpdating
|Run|Job|Step|
|------------|--------|----|
|[13048816319](https://github.com/stianst/keycloak/actions/runs/13048816319)|Clustering IT|cluster tests|

### org.keycloak.testsuite.cluster.ComponentInvalidationClusterTest#crudWithoutFailover
|Run|Job|Step|
|------------|--------|----|
|[13048816319](https://github.com/stianst/keycloak/actions/runs/13048816319)|Clustering IT|cluster tests|

### org.keycloak.testsuite.cluster.ComponentInvalidationClusterTest#crudWithFailover
|Run|Job|Step|
|------------|--------|----|
|[13048816319](https://github.com/stianst/keycloak/actions/runs/13048816319)|Clustering IT|cluster tests|

### org.keycloak.testsuite.cluster.GroupInvalidationClusterTest#crudWithoutFailover
|Run|Job|Step|
|------------|--------|----|
|[13048816319](https://github.com/stianst/keycloak/actions/runs/13048816319)|Clustering IT|cluster tests|

### org.keycloak.testsuite.cluster.PermissionTicketInvalidationClusterTest#crudWithoutFailover
|Run|Job|Step|
|------------|--------|----|
|[13048815282](https://github.com/stianst/keycloak/actions/runs/13048815282)|Clustering IT|cluster tests|

### org.keycloak.testsuite.cluster.PermissionTicketInvalidationClusterTest#crudWithFailover
|Run|Job|Step|
|------------|--------|----|
|[13048815282](https://github.com/stianst/keycloak/actions/runs/13048815282)|Clustering IT|cluster tests|

### org.keycloak.testsuite.cluster.RealmInvalidationClusterTest#crudWithoutFailover
|Run|Job|Step|
|------------|--------|----|
|[13048815282](https://github.com/stianst/keycloak/actions/runs/13048815282)|Clustering IT|cluster tests|

### org.keycloak.testsuite.cluster.RealmInvalidationClusterTest#crudWithFailover
|Run|Job|Step|
|------------|--------|----|
|[13048815282](https://github.com/stianst/keycloak/actions/runs/13048815282)|Clustering IT|cluster tests|

### org.keycloak.testsuite.cluster.RoleInvalidationClusterTest#crudWithoutFailover
|Run|Job|Step|
|------------|--------|----|
|[13048815282](https://github.com/stianst/keycloak/actions/runs/13048815282)|Clustering IT|cluster tests|

### org.keycloak.testsuite.cluster.RoleInvalidationClusterTest#crudWithFailover
|Run|Job|Step|
|------------|--------|----|
|[13048815282](https://github.com/stianst/keycloak/actions/runs/13048815282)|Clustering IT|cluster tests|

**Comment by douglaspalmer** [comment]
@stianst I've tweaked the PR again; ran 100 times without failure. Would you try it again please?
https://github.com/douglaspalmer/keycloak/actions/runs/13061689529
https://github.com/keycloak/keycloak/pull/36884

**Comment by pruivo** [comment]
I'm having a bad time reproducing failures. I did run 100 times in the main branch, and it was no luck for me. If anyone sees any failures in the main branch pasted here, please. 
https://github.com/pruivo/keycloak/actions/runs/13701043754

**Comment by ahus1** [comment]
There are now several fixes applied. This is now stable enough. 

225 successful runs: https://github.com/mhajas/keycloak/actions/runs/14195094051
