### ISSUE TITLE
Keycloak container incorrectly read CGroups settings on Kernel 6.12

### ISSUE THREAD

**Issue by slaskawi** [keycloak/keycloak#36609]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Main tracking issue: https://github.com/defenseunicorns/uds-core/issues/1212

When using Fedora F41 (kernel 6.12 line), Keycloak Pod get OOM Killed. The root cause can clearly be seen when manually calling the following command from the Keycloak Pod:

Kernel 6.11 (Good):
```
sh-5.1$ java -XshowSettings:vm -version
    Max. Heap Size (Estimated): 247.50M <-- !!!
...
    Provider: cgroupv2
    Effective CPU Count: 1 <-- !!!
```

Kernel 6.12 (Bad):
```
sh-5.1$ java -XshowSettings:vm -version
...
    Max. Heap Size (Estimated): 7.67G <-- !!! This is the Node value!
...
    Provider: cgroupv2
    Effective CPU Count: 16 <-- !!! Again, taken from the Node!
```

The issue has already been reported in [JDK-8346874](https://bugs.openjdk.org/browse/JDK-8346874) that follows to the actual fix - [JDK-8347129](https://bugs.openjdk.org/browse/JDK-8347129). At the time of writing, this has been fixed only in the latest JVM versions with no information about the backports

### Version

26.0.8

### Regression

- [ ] The issue is a regression

### Expected behavior

Memory should be properly interpreted

### Actual behavior

Memory is being pulled from the Node running the container

### How to Reproduce?

Deploy Keycloak on Fedora F41 (any Kubernetes distribution that doesn't use Virtual Machines, for example k3d) with Kernel 6.12 onwards

**Comment by slaskawi** [comment]
The issue is related to this change in the Linux kernel: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=af000ce85293b8e608f696f0c6c280bc3a75887f

**Comment by shawkins** [comment]
Backports are now listed for 24.0.1 and 21.0.7, but nothing for 17 so I think this should be marked as important for further investigation / documentation.

~priority-important

**Comment by slaskawi** [comment]
Thanks a million @shawkins for the update! Highly appreciated!

@shawkins @stianst @pskopek Could you please advice, when we can expect a Keycloak release based on one of the above JVM versions? Is it just a matter of getting a Pull Request or we're tied into the Product release cycle and it will take a bit longer?

If this is a matter of just getting a Pull Request I can probably arrange some time to look into this later next week. If it's a release coordination issue, than we might want to follow up with the JVM Team and ask for a backport to 17.

**Comment by vmuzikar** [comment]
Even though this affects Keycloak, if I understand correctly the fix will have to be completely at JDK side. In our dockerfile we don't even specify the exact Java version down to patch release, so no need to do any changes there either. (Not sure about RHBK though. CC @ASzc). I am adding blocked-external label just to keep this issue as the tracker, but it'll be fixed implicitly.

A backport to JDK 17 would be required for RHBK 24 which is still supported.

This issue affects mostly our [container specific memory settings](https://github.com/keycloak/keycloak/blob/b2e8942dd1a4d931491bd25a4671e5aaac36c380/quarkus/dist/src/main/content/bin/kc.sh#L103-L106), not sure if there are other areas. For this, the workaround would be to override the `KC_RUN_IN_CONTAINER` env var and set it to `false`.

**Comment by vmuzikar** [comment]
OpenJDK 21.0.7 seems to have [ETA set to Apr 15](https://wiki.openjdk.org/display/JDKUpdates/JDK+21u).

**Comment by ASzc** [comment]
Product doesn't pin an exact JDK version either, so if affected the fix would be available on the first build after OpenJDK releases a fix

**Comment by vmuzikar** [comment]
Keycloak 26.2.1 is using OpenJDK 21.0.7 already. I am resolving the issue.  Feel free to reopen if it's still valid.

**Comment by slaskawi** [comment]
It seems this issue still persists. Here's a small verification command and the output from my M2 Mac:

```
docker run -it --memory 1G --entrypoint java quay.io/keycloak/keycloak:26.2.5 "-XshowSettings:vm -Xlog:os+container=trace --version"
...
VM settings:
    Max. Heap Size (Estimated): 3.96G <-- This should be 1G
    Using VM: OpenJDK 64-Bit Server VM
...
    java.vendor.version = (Red_Hat-21.0.7.0.6-1)
    java.version = 21.0.7
```

When I started digging more into this, apparently the problem is in CGroups controllers, which suggests it's related to [JDK-8346874](https://bugs.openjdk.org/browse/JDK-8346874):

```
# Called inside of the Keycloak Docker container
$ java -Xlog:os+container=trace --version
[0.000s][trace][os,container] OSContainer::init: Initializing Container Support
[0.000s][debug][os,container] Detected optional pids controller entry in /proc/cgroups
[0.000s][debug][os,container] controller cpuset is not enabled

[0.000s][debug][os,container] controller memory is not enabled

[0.000s][debug][os,container] One or more required controllers disabled at kernel level.
openjdk 21.0.7 2025-04-15 LTS
OpenJDK Runtime Environment (Red_Hat-21.0.7.0.6-1) (build 21.0.7+6-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.7.0.6-1) (build 21.0.7+6-LTS, mixed mode, sharing)
```

The JDK Ticket has a fix version of JDK 25 (which should be GA on 2025/09/16). @ASzc @vmuzikar @shawkins Do you know when do we plan to switch into a newer JDK?

**Comment by vmuzikar** [comment]
Sounds like we should re-open this.

**Comment by thomasdarimont** [comment]
Keycloak 26.3.2 seems to look okay?... same value as in the first post for "Max. Heap Size (Estimated): 247.50M"
```
$ docker run -it --memory 1G --entrypoint java quay.io/keycloak/keycloak:26.3.2 "-XshowSettings:vm -Xlog:os+container=trace --version"
Unable to find image 'quay.io/keycloak/keycloak:26.3.2' locally
26.3.2: Pulling from keycloak/keycloak
Digest: sha256:922e443a962b8ad0dffa3c17061e8136583d7bc59209a1d1fc059816467c3f69
Status: Downloaded newer image for quay.io/keycloak/keycloak:26.3.2
VM settings:
    Max. Heap Size (Estimated): 247.50M
    Using VM: OpenJDK 64-Bit Server VM
```

**Comment by FirelightFlagboy** [comment]
> Keycloak 26.3.2 seems to look okay?... same value as in the first post for "Max. Heap Size (Estimated): 247.50M"

Sadly, not on my side:

```
docker run -it --memory 1G --entrypoint java quay.io/keycloak/keycloak:26.3.2 -Xlog:os+container=trace -XshowSettings:vm -version
```

Log:

```
[0.000s][trace][os,container] OSContainer::init: Initializing Container Support
[0.000s][debug][os,container] Detected optional pids controller entry in /proc/cgroups
[0.000s][debug][os,container] controller cpuset is not enabled

[0.000s][debug][os,container] controller memory is not enabled

[0.000s][debug][os,container] One or more required controllers disabled at kernel level.
VM settings:
    Max. Heap Size (Estimated): 7.82G
    Using VM: OpenJDK 64-Bit Server VM

openjdk version "21.0.8" 2025-07-15 LTS
OpenJDK Runtime Environment (Red_Hat-21.0.8.0.9-1) (build 21.0.8+9-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.8.0.9-1) (build 21.0.8+9-LTS, mixed mode, sharing)
```

Kernel:

```
$ cat /proc/version
Linux version 6.12.34 (nixbld@localhost) (gcc (GCC) 14.3.0, GNU ld (GNU Binutils) 2.44) #1-NixOS SMP PREEMPT_DYNAMIC Thu Jun 19 13:32:38 UTC 2025
```

**Comment by mabartos** [comment]
Looks good to me as well for 26.3.2. EDIT: Not related to the issue entirely - Used Kernel version 6.15.5.

Execute:
```
docker run -it --memory 1G --entrypoint java quay.io/keycloak/keycloak:26.3.2 -Xlog:os+container=trace -XshowSettings:vm -version
```

Log:
```
[0.001s][trace][os,container] Path to /memory.max is /sys/fs/cgroup/memory.max
[0.001s][trace][os,container] Raw value for memory limit is: 1073741824
[0.001s][trace][os,container] Memory Limit is: 1073741824
[0.002s][trace][os,container] CgroupSubsystem::active_processor_count (cached): 20
[0.012s][trace][os,container] CgroupSubsystem::active_processor_count (cached): 20
VM settings:
    Max. Heap Size (Estimated): 247.50M
    Using VM: OpenJDK 64-Bit Server VM

openjdk 21.0.8 2025-07-15 LTS
OpenJDK Runtime Environment (Red_Hat-21.0.8.0.9-1) (build 21.0.8+9-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.8.0.9-1) (build 21.0.8+9-LTS, mixed mode, sharing)

```

Kernel version (6.15.5):

```
sh-5.1$ cat /proc/version 
Linux version 6.15.5-100.fc41.x86_64 (mockbuild@6b18bd9bce6c4a769ef8f7af2b9e8c64) (gcc (GCC) 14.3.1 20250523 (Red Hat 14.3.1-1), GNU ld version 2.43.1-5.fc41) #1 SMP PREEMPT_DYNAMIC Sun Jul  6 10:18:41 UTC 2025
```

EDIT: Kernel version 6.15.x, so the issue should be fixed on that side, but depends on the underlying machine.

**Comment by mabartos** [comment]
@vmuzikar As you have assigned this issue, could you please triage it based on the findings above? I believe it might be closed after the full review of the latest images. Thanks

**Comment by slaskawi** [comment]
@mabartos I've just tested the 26.3.2 image with my M2 Mac and the problem still appears:

```
docker run -it --memory 1G --entrypoint java quay.io/keycloak/keycloak:26.3.2 -Xlog:os+container=trace -XshowSettings:vm -version
Unable to find image 'quay.io/keycloak/keycloak:26.3.2' locally
26.3.2: Pulling from keycloak/keycloak
a8e003c3f453: Download complete
bfde20b382a3: Download complete
ff8801ac357f: Download complete
5ad0bbc7f6d1: Download complete
Digest: sha256:922e443a962b8ad0dffa3c17061e8136583d7bc59209a1d1fc059816467c3f69
Status: Downloaded newer image for quay.io/keycloak/keycloak:26.3.2
[0.000s][trace][os,container] OSContainer::init: Initializing Container Support
[0.000s][debug][os,container] Detected optional pids controller entry in /proc/cgroups
[0.000s][debug][os,container] controller cpuset is not enabled

[0.000s][debug][os,container] controller memory is not enabled

[0.000s][debug][os,container] One or more required controllers disabled at kernel level.
VM settings:
    Max. Heap Size (Estimated): 3.96G
    Using VM: OpenJDK 64-Bit Server VM

openjdk version "21.0.8" 2025-07-15 LTS
OpenJDK Runtime Environment (Red_Hat-21.0.8.0.9-1) (build 21.0.8+9-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.8.0.9-1) (build 21.0.8+9-LTS, mixed mode, sharing)
```

As I mentioned in one of my previous comments (https://github.com/keycloak/keycloak/issues/36609#issuecomment-3106624102), I suspect this might be related to JDK-8346874, which will get fixed in JDK 25. Having said that, I think we should keep this issue open.

**Comment by FirelightFlagboy** [comment]
I confirm that on openjdk-25 the issue is solved (but persist for version 21 to 24)

```shell
docker run -it --rm --memory 1G --entrypoint bash openjdk:25
```

```
$ java -Xlog:os+container=trace -XshowSettings:vm -version
[0.003s][trace][os,container] OSContainer::init: Initializing Container Support
[0.003s][debug][os,container] Detected optional cpuset controller entry in /sys/fs/cgroup/cgroup.controllers
[0.003s][debug][os,container] Detected optional pids controller entry in /sys/fs/cgroup/cgroup.controllers
[0.004s][debug][os,container] Detected cgroups v2 unified hierarchy
[0.004s][debug][os,container] OSContainer::init: is_containerized() = true because all controllers are mounted read-only (container case)
[0.004s][trace][os,container] Path to /cpu.max is /sys/fs/cgroup/cpu.max
[0.004s][trace][os,container] CPU Quota is: -1
[0.004s][trace][os,container] Path to /cpu.max is /sys/fs/cgroup/cpu.max
[0.004s][trace][os,container] CPU Period is: 100000
[0.004s][trace][os,container] OSContainer::active_processor_count: 16
[0.004s][trace][os,container] CgroupSubsystem::active_processor_count (cached): 16
[0.004s][trace][os,container] total physical memory: 33557782528
[0.004s][trace][os,container] Path to /memory.max is /sys/fs/cgroup/memory.max
[0.004s][trace][os,container] Memory Limit is: 1073741824
[0.004s][trace][os,container] Memory Limit is: 1073741824
[0.019s][trace][os,container] CgroupSubsystem::active_processor_count (cached): 16
[0.020s][trace][os,container] CgroupSubsystem::active_processor_count (cached): 16
[0.033s][trace][os,container] Path to /cpu.max is /sys/fs/cgroup/cpu.max
[0.033s][trace][os,container] CPU Quota is: -1
[0.033s][trace][os,container] Path to /cpu.max is /sys/fs/cgroup/cpu.max
[0.033s][trace][os,container] CPU Period is: 100000
[0.033s][trace][os,container] OSContainer::active_processor_count: 16
VM settings:
[0.046s][trace][os,container] CgroupSubsystem::active_processor_count (cached): 16
    Max. Heap Size (Estimated): 247.50M
    Using VM: OpenJDK 64-Bit Server VM

openjdk version "25-ea" 2025-09-16
OpenJDK Runtime Environment (build 25-ea+34-3482)
OpenJDK 64-Bit Server VM (build 25-ea+34-3482, mixed mode, sharing)
```

Kernel: 

```
Linux version 6.12.40 (nixbld@localhost) (gcc (GCC) 14.3.0, GNU ld (GNU Binutils) 2.44) #1-NixOS SMP PREEMPT_DYNAMIC Thu Jul 24 06:56:38 UTC 2025
```

**Comment by slaskawi** [comment]
Thanks @FirelightFlagboy! I ran the same check and got results similar to yours. JDK 25 seems to solve this problem entirely!

**Comment by mabartos** [comment]
@slaskawi @FirelightFlagboy I see, thanks for the additional information - let's keep it open.

**Comment by mabartos** [comment]
Just for a better addressability - I believe here's the ticket for backporting it into JDK 17 and JDK 21: https://bugs.openjdk.org/browse/JDK-8359817

**Comment by mabartos** [comment]
Based on the ticket, it seems the issue is still not resolved. Does anybody have any updates on this? Would it be possible to vote up on that JDK issue or put some comment there?

**Comment by slaskawi** [comment]
I believe this issue might go away when we adapt JDK 25: https://github.com/keycloak/keycloak/issues/43265

**Comment by mabartos** [comment]
Just to add a little bit more information:

For JDK 25, where the issue is solved based on the findings above, the container detection mechanism for various controllers points to the `/sys/fs/cgroup/cgroup.controllers`, which leads to the CGroups v2. Then the detection mechanism works as expected, and it's properly set. 

As seen in the "non-working" reproducers above, the detection mechanism is trying to leverage the `/proc/cgroups`, which is mostly relevant to cgroups v1, and potentially even the memory controller does not work properly.

See: 
- https://bugs.openjdk.org/browse/JDK-8347811
- https://bugs.openjdk.org/browse/JDK-8349527

The detection mechanism should be fixed in the OpenJDK 21.0.10 (Tuesday, January 20 2026 GA): https://bugs.openjdk.org/browse/JDK-8371005

-------------------------

When some required controller is disabled, like `cpu`, `memory` or `cpuset` (was required in older JDK micro releases), the resources should be set based on the host resources. So, even the issue with `cpuset` considered as required controller should be prerequisite to resolve this issue completely. But if you see the "Detected optional cpuset controller entry..." in your log, your JDK should already [contain the fix](https://github.com/openjdk/jdk21u-dev/commit/be245be258cda7e06366b4051eec24ad6df04f20#diff-3361dc60a8419968e04c70ee433f2498369962a3eed02cfffcf1546a324c4f1dR198).

See: 
- https://bugs.openjdk.org/browse/JDK-8347129
---------------------

### Summary
It means that the issue we're tracking here (https://bugs.openjdk.org/browse/JDK-8359817) does not fully reflect the current state of the original issue (https://bugs.openjdk.org/browse/JDK-8347811).

The original issue has already been backported to the OpenJDK 21 branch and will be part of the OpenJDK 21.0.10 release.

**Therefore, this issue should be fully resolved once the new OpenJDK 21.0.10 is released**:
- OpenJDK 21.0.10 (Tuesday, January 20 2026 GA)

**Comment by ahus1** [comment]
@vmuzikar - I'm removing the release tags from this issue as it seems not fixed yet.

**Comment by shawkins** [comment]
@ahus1 @pskopek @mabartos given that the release was today, a respin may address this and #45459

**Comment by ahus1** [comment]
@shawkins - I'm not sure if it has landed in Red Hat's UBI yet. Only then would a respin make sense.

I just did a local build and it still pulled `1:21.0.9.0.10-2.el9` which is then not 21.0.10.x yet. 
I've marked it to with the 26.6.0 milestone so we can re-assess it before the release at the latest (and provide backports by respin as suggested).

**Comment by shawkins** [comment]
> Only then would a respin make sense.

Correct, I mean after we can pick up 21.0.10.

**Comment by mabartos** [comment]
The OpenJDK 21.0.10 should be available now for the Red Hat UBI 9. 

<img width="1257" height="382" alt="Image" src="https://github.com/user-attachments/assets/197c148f-e4ed-430a-8e44-7e0e7d98ad47" />

So, we should be able to respin. 

cc: @ahus1 @shawkins @abstractj @stianst

**Comment by mabartos** [comment]
Closing now, as Keycloak 26.5.2 now uses Java 21.0.10.

Backports for 26.4 mean image respin. 

@vmuzikar I see that you have assigned this issue. Would it be possible to move on with the respins?

**Comment by ahus1** [comment]
Removed backport label as this will be part of the next 26.4.x RHBK image respin without any additional actions.
