### ISSUE TITLE
Login[v2]: Email confirmation link expired page/text is confusing

### ISSUE THREAD

**Issue by SebastEnn** [keycloak/keycloak#38574]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

When I register a new user, I have to confirm his email address by clicking a link from an email sent by Keycloak.
If this link has expired, I get an error.

This is the error when the link is opened in the same browser from where the registration took place:
![Image](https://github.com/user-attachments/assets/4c04bd39-1d06-4478-ac23-5a428c44febb)

This is the error when the link is opened in a different browser with no active login session:
![Image](https://github.com/user-attachments/assets/757317c9-338e-4a20-ba25-987a875137fd)

For generic error messages for every expired action of Keycloak this would be fine, but I got feedback from my customers that in the scenario of email confirmation this is confusing. So I would like to edit these error messages in my extended theme just for this case, but I can't because they would be displayed in any other scenario as well. 

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

The error messages in case of an expired email confirmation link express the problem properly.

### Actual behavior

The error messages are too generic and can't be changed for individual cases.

### How to Reproduce?

- Create a realm
- Enable registration
- Enable and setup email verification
- For debugging: Set action token timeout for email verification to 1 second
- Try registration
- Receive email with confirmation link
- Open link in the same browser and in an incognito window or other browser (for cookie separation)

### Anything else?

Technical details:
The message keys of the error texts are `errorTitle`, `expiredActionTokenNoSessionMessage` and `expiredActionTokenSessionExistsMessage`.

**Comment by mposolda** [comment]
@SebastEnn Thanks for the report. Could you please doublecheck on latest Keycloak 26.2 release? It is possible that this is already fixed.

**Comment by SebastEnn** [comment]
I can confirm that this issue is still present in the latest release (26.2.3).

@mposolda please reopen this issue.

**Comment by SebastEnn** [comment]
Please reopen. This issue is still present and affects more people (see 👍-count & [this comment](https://github.com/keycloak/keycloak/issues/38575#issuecomment-3382067798)).
