### ISSUE TITLE
Multi-stage docker builds fail --optimized validation

### ISSUE THREAD

**Issue by MarcusDunn** [keycloak/keycloak#38893]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Running a dockerfile with `--optimized` that works with earlier versions fails on newer ones. I believe the commit is: https://github.com/keycloak/keycloak/commit/332bf122f1af16b4187af5ecc3129bd63e504335.

The error is: `A provider JAR was updated since the last build, please rebuild for this to be fully utilized.`

This may be similar to https://github.com/keycloak/keycloak/issues/37770, but they seemed to have resolved the issue.

### Version

26.2

### Regression

- [ ] The issue is a regression

### Expected behavior

This docker image can be run fine with --optimized

### Actual behavior

It fails with `ERROR: A provider JAR was updated since the last build, please rebuild for this to be fully utilized.`

### How to Reproduce?

I have the following dockerfile leveraging [keycloakify](https://www.keycloakify.dev/):

```Dockerfile
FROM node:22@sha256:0e910f435308c36ea60b4cfd7b80208044d77a074d16b768a81901ce938a62dc AS keycloakify_jar_builder

RUN wget -O - https://apt.corretto.aws/corretto.key | gpg --dearmor -o /usr/share/keyrings/corretto-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/corretto-keyring.gpg] https://apt.corretto.aws stable main" | tee /etc/apt/sources.list.d/corretto.list && \
    apt-get update && \
    apt-get install -y java-21-amazon-corretto-jdk && \
    apt-get install -y maven;

COPY package.json package-lock.json /opt/app/

WORKDIR /opt/app

RUN npm ci

COPY . /opt/app/

RUN npm run build-keycloak-theme

FROM quay.io/keycloak/keycloak:26.2@sha256:87758ff2293c78c942c7a1f0df2bc13e0f943fcf0c0d027c12fdfac54a35d93b

WORKDIR /opt/keycloak
COPY --from=keycloakify_jar_builder /opt/app/dist_keycloak/keycloak-theme-for-kc-all-other-versions.jar /opt/keycloak/providers/
RUN /opt/keycloak/bin/kc.sh build --db=postgres --health-enabled=true --metrics-enabled=true --tracing-enabled=true --features=opentelemetry:v1,multi-site:v1
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

After building, running `docker run 24f554b83ada start --optimized` yeilds:

`ERROR: A provider JAR was updated since the last build, please rebuild for this to be fully utilized.`

I am not sure what causes this. I think it may have to do with docker COPY messing with timestamps, but don't know enough to be sure.

For now I can run unoptimized, but this is not ideal.

### Anything else?

Running `docker run <image hash> show-config` yeilds:
```
Current Mode: production
Current Configuration:
        kc.health-enabled =  true (Persisted)
        kc.provider.file.keycloak-theme-for-kc-all-other-versions.jar.last-modified =  1744417140193 (Persisted)
        kc.log-level-org.jboss.resteasy.resteasy_jaxrs.i18n =  WARN (classpath application.properties)
        kc.log-level-io.quarkus.arc.processor.BeanArchives =  off (classpath application.properties)
        kc.log-level-io.quarkus.deployment.steps.ReflectiveHierarchyStep =  error (classpath application.properties)
        kc.tracing-enabled =  true (Persisted)
        kc.log-level-org.infinispan.transaction.lookup.JBossStandaloneJTAManagerLookup =  WARN (classpath application.properties)
        kc.tracing-jdbc-enabled =  true (Persisted)
        kc.log-level-io.quarkus.config =  off (classpath application.properties)
        kc.log-console-output =  default (classpath application.properties)
        kc.metrics-enabled =  true (Persisted)
        kc.log-level-io.quarkus.arc.processor.IndexClassLookupUtils =  off (classpath application.properties)
        kc.db =  postgres (Persisted)
        kc.log-level-io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor =  warn (classpath application.properties)
        kc.optimized =  true (Persisted)
        kc.version =  26.2.0 (SysPropConfigSource)
        kc.features =  opentelemetry:v1,multi-site:v1 (Persisted)
        kc.run-in-container =  true (ENV)
```

**Comment by shawkins** [comment]
> I am not sure what causes this. I think it may have to do with docker COPY messing with timestamps, but don't know enough to be sure.

I don't think we've seen this behavior before. But our example shows using ADD, instead of COPY, so that the ownership of the provider jar can also be set - maybe there's a difference between ADD and COPY coming into play here https://www.keycloak.org/server/containers#_writing_your_optimized_keycloak_containerfile

> kc.provider.file.keycloak-theme-for-kc-all-other-versions.jar.last-modified =  1744417140193 (Persisted)

Out of curiosity could you also determine what the actual last-modified time of the provider jar is at runtime?

**Comment by bahaa** [comment]
I'm not sure this is the cause or not. But I face the same error when I try to build the image on a machine that has `Docker version 24.0.2, build cb74dfc`, but when I tried to build the same image on a machine with `Docker version 27.5.1, build 9f9e405` or `Docker version 28.0.4, build b8034c0ed7` it worked just fine.

**Comment by MarcusDunn** [comment]
> I'm not sure this is the cause or not. But I face the same error when I try to build the image on a machine that has `Docker version 24.0.2, build cb74dfc`, but when I tried to build the same image on a machine with `Docker version 27.5.1, build 9f9e405` or `Docker version 28.0.4, build b8034c0ed7` it worked just fine.

```bash
docker -v
Docker version 27.5.1, build 9f9e405
```

 > Out of curiosity could you also determine what the actual last-modified time of the provider jar is at runtime?

I'm not sure of an easy way to inspect the modified time at runtime. But these are the `stat`s. (Access and Modify matches the unixtime in the config, Change and Birth are after)

```bash
stat keycloak-theme-for-kc-all-other-versions.jar 
  File: keycloak-theme-for-kc-all-other-versions.jar
  Size: 1763566         Blocks: 3448       IO Block: 4096   regular file
Device: 7ch/124d        Inode: 33870099    Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2025-04-12 00:19:00.000000000 +0000
Modify: 2025-04-12 00:19:00.000000000 +0000
Change: 2025-04-12 00:35:45.753114012 +0000
Birth: 2025-04-12 00:35:45.747114012 +000
```

> I don't think we've seen this behavior before. But our example shows using ADD, instead of COPY, so that the ownership of the provider jar can also be set - maybe there's a difference between ADD and COPY coming into play here https://www.keycloak.org/server/containers#_writing_your_optimized_keycloak_containerfile

I think I have to `COPY`, `ADD` will not work with multi-stage builds.

**Comment by MarcusDunn** [comment]
found a jankier but functional workaround:

```Dockerfile
RUN touch -m --date=@1744481906 /opt/keycloak/providers/keycloak-theme-for-kc-all-other-versions.jar
```

I don't see many drawbacks of this.

**Comment by bahaa** [comment]
@shawkins changing `COPY` to `ADD --chown=keycloak:keycloak --chmod=644 ...` didn't fix the issue for me.

**Comment by dejwsz** [comment]
For us this helped in our multi-stage Dockerfile:
1. Copy everything like provider, themes with chown: `COPY --chown=keycloak:keycloak ...`
2. Touch the provider jar and fix its timestamp back in time before optimized build like:
```
RUN date -d "$(date -u -R) -1 hour" +%Y%m%d%H%M.%S | xargs -I{} touch -m -t {} /opt/keycloak/providers/my-test-spi-jar-with-dependencies.jar && /opt/keycloak/bin/kc.sh build
```
Chown is required to be able to modify the jar timestap, otherwise you get permission denied error.

**Comment by bdovaz** [comment]
> For us this helped in our multi-stage Dockerfile:
> 
> 1. Copy everything like provider, themes with chown: `COPY --chown=keycloak:keycloak ...`
> 2. Touch the provider jar and fix its timestamp back in time before optimized build like:
> 
> ```
> RUN touch -m -t "$(date -u -d '1 hour ago' +%Y%m%d%H%M.%S)" /opt/keycloak/providers/my-test-spi-jar-with-dependencies.jar && /opt/keycloak/bin/kc.sh build
> ```
> 
> Chown is required to be able to modify the jar timestamp, otherwise you get permission denied error.

It has worked for us but this indicates that somehow it has to be a regression created in 26.2.0.... It doesn't make sense that this has to be done when it was not necessary until now.

**Comment by shawkins** [comment]
> it has to be a regression created in 26.2.0

I wouldn't call this a regression as it's working as intended #34665

It seems more like an issue with specific versions of Docker not maintaining file timestamps.

**Comment by dejwsz** [comment]
I did not analyze it too deep but it looks like it is related somehow to the new version of quarkus used in this new release, so 3.17.x (https://github.com/keycloak/keycloak/issues/36501). The reaugmentation process (https://quarkus.io/guides/reaugmentation) which depends on involved files timestamps, I can see in the keycloak sources the flag is used `builder.setProperty("quarkus.launch.rebuild", "true");` - so any rebuild should be done during the process? Maybe here in a multi-stage dockerfile setup this "manual" copy of a provider jar messes up too much with the file timestamp and this makes the process break ? https://github.com/keycloak/keycloak/blob/4cb4d2d06ed17e3a8bd928f472d3f9e4d1adea1d/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Build.java#L78

**Comment by shawkins** [comment]
@dejwsz the checking of provider jar timestamps is purely on the Keycloak side of things https://github.com/keycloak/keycloak/issues/34665

**Comment by dejwsz** [comment]
> > it has to be a regression created in 26.2.0
> 
> I wouldn't call this a regression as it's working as intended [#34665](https://github.com/keycloak/keycloak/issues/34665)
> 
> It seems more like an issue with specific versions of Docker not maintaining file timestamps.

Interesting is with 26.1.5 we did not have the issue at all - our Dockerfile was exactly the same with exception to keycloak base image version.

**Comment by shawkins** [comment]
> Interesting is with 26.1.5 we did not have the issue at all - our Dockerfile was exactly the same with exception to keycloak base image version.

#34665 was added in 26.2.

**Comment by dejwsz** [comment]
So to summarize (if I understood it well):
1. If a provider jar is built in a different stage and we copy it, we just need to modify its timestamp to fool the keycloak / quarkus build process ? no other way to go here
2. Build a provider jar and keycloak image in a one, common stage and it should work then just fine ?

**Comment by dejwsz** [comment]
> > it has to be a regression created in 26.2.0
> 
> I wouldn't call this a regression as it's working as intended [#34665](https://github.com/keycloak/keycloak/issues/34665)
> 
> It seems more like an issue with specific versions of Docker not maintaining file timestamps.

I guess you're may be right, we made those builds in gh runners with docker engine 26.x which was reported with this kind of problems. They plan to upgrade it soon: https://github.com/actions/runner-images/issues/11766 what should solve this problem I guess. We did not have the issue in our local system using one of the latest 28.x docker engine.

**Comment by bahaa** [comment]
BTW, upgrading Docker Engine to 28.x didn't fix the issue. Here's the output of `docker version` on the machine that has the issue:
```
Client: Docker Engine - Community
Version:           28.0.4
API version:       1.48
Go version:        go1.23.7
Git commit:        b8034c0
Built:             Tue Mar 25 15:07:11 2025
OS/Arch:           linux/amd64
Context:           default
Server: Docker Engine - Community
Engine:
  Version:          28.0.4
  API version:      1.48 (minimum version 1.24)
  Go version:       go1.23.7
  Git commit:       6430e49
  Built:            Tue Mar 25 15:07:11 2025
  OS/Arch:          linux/amd64
  Experimental:     false
containerd:
  Version:          1.7.27
  GitCommit:        05044ec0a9a75232cad458027ca83437aae3f4da
runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 ```

**Comment by dejwsz** [comment]
so my assumption about docker version was wrong in that case - anyway the solution we used shoud not break anything so we will live with it for the moment

**Comment by dejwsz** [comment]
To add more, we tried to build our provider jar and keycloak in the same stage and it also did not help, still the same error. It looks like a docker engine version also has nothing to do with it. So still a kind of puzzle. Anyway timestamp modification for the provider's jar helps.

**Comment by ibauersachs** [comment]
We also ran into this issue and are currently working around it by modifying the file timestamp.

In any case, IMO file timestamps shouldn't be used for this kind of verification. A hash of the jar would be much better suited, or since it's not security relevant here, even a CRC would be enough and more reliable.

**Comment by dejwsz** [comment]
> [@dejwsz](https://github.com/dejwsz) the checking of provider jar timestamps is purely on the Keycloak side of things [#34665](https://github.com/keycloak/keycloak/issues/34665)

so maybe this way of solving it is not the right one then, like on relying on timestamps only

**Comment by shawkins** [comment]
Looking into to this more there are some references that a plain copy or add operation does indeed have counterintuative affects on the mtime of files - it will be one value at build time, then in the image it will be stored as the image creation time.

There are a couple of suggestions for making thing consistent. From https://docs.docker.com/build/ci/github-actions/reproducible-builds/ you can use SOURCE_DATE_EPOCH, it also appears that COPY --link preserves the original file attributes.

Seems like we do need to update our example.

> In any case, IMO file timestamps shouldn't be used for this kind of verification. A hash of the jar would be much better suited, or since it's not security relevant here, even a CRC would be enough and more reliable.

I am not sure what motivated the original decision to use timestamps. I believe that it was considered good enough for most most circumstances with out any performance implications. A CRC32 or other fast hash could prevent false positives from changing timestamps, but we'd need to vet the performance. I agree that there aren't security concerns here with a non-cryptographic given that the primary issue would be having something sensitive in the provider jars.

However this situation does seem to be more of a nuance of Docker that can be addressed in other ways.

**Comment by fruwe** [comment]
PS: I used this as a workaround:

```Dockerfile
RUN find /opt/keycloak/providers -name '*.jar' -exec bash -c ' \
  for f; do \
  epoch_sec=$(stat -c %Y "$f"); \
  touch -d @"$epoch_sec" "$f"; \
  done' bash {} +
```

**Comment by MarcusDunn** [comment]
from a keycloak perspective, would it be possible to use a checksum of the jar instead of a timestamp? This seems to capture the intent of the check better, but comes with some overhead.

**Comment by shawkins** [comment]
> from a keycloak perspective, would it be possible to use a checksum of the jar instead of a timestamp? This seems to capture the intent of the check better, but comes with some overhead.

Beyond the workarounds that can be done on the docker side of things, I see a couple of options for Keycloak:

1. use a checksum instead. My concern there is that isn't generally needed and adds startup cost that really isn't needed here either.
2. A system property or option to indicate that the provider directory is read-only to skip this check.
3. Change the check from an error to a warning - the worst case is that the augmentation state is out-of-date, so people putting in new jars and miss this warning could be initially confused when they see their stuff either not used, or class loading errors.

**Comment by shawkins** [comment]
Removed that this is a regression - instead we should be looking towards doc changes, or an enhancement / refinement like mentioned in the previous comment.

**Comment by MarcusDunn** [comment]
for what it's worth, he's a plot of running `sha256sum` on every jar `find` could find on my computer:

![Image](https://github.com/user-attachments/assets/b3304e5f-b6a1-4baf-9abc-997f1465b62a)

**Comment by shawkins** [comment]
cc @keycloak/cloud-native - TLDR docker builds without additional steps does weird things with file modification timestamps, which throws off our detection of provider jar changes.

See https://github.com/keycloak/keycloak/issues/38893#issuecomment-2810235439 for possible remediation. Let me know your thoughts.

I'm marking this as important for now.

**Comment by shawkins** [comment]
Trying to understand better the conditions under which this is happening. Locally tried a simplified keycloakify example:

```
FROM node:20-alpine as build
RUN apk update && apk add --no-cache git openjdk21 maven
WORKDIR /app
COPY . .
RUN yarn install --frozen-lockfile
RUN yarn build-keycloak-theme

FROM quay.io/keycloak/keycloak:latest
WORKDIR /opt/keycloak
COPY --from=build /app/dist_keycloak/keycloak-theme-for-kc-all-other-versions.jar /opt/keycloak/providers/
RUN /opt/keycloak/bin/kc.sh build
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--optimized"]
```

And just an example copying a provider jar from a URL. They both built and started just fine with both Docker and podman on my rhel system. 

Could others provide the details of their Docker install / OS that may help identify better how to reproduce this behavior?

**Comment by bahaa** [comment]
Here are all the facts I know so far:
* I build the provider jars on the host machine then add them to the container using `ADD` or `COPY`.
* The same docker file worked just fine on local macOS. I never faced this issue on macOS (I'm using Lima as Docker engine).
* When I try to build the image on a Linux EC2 (our CI system) and deploy it to Kubernetes the issue starts to happen.
* I tried different Docker versions and this didn't fix the issue.
* The issue got fixed only after the files got touched using `RUN touch -m --date=@1743465600 /opt/keycloak/providers/*`.

Our Dockerfile looks like this:
```dockerfile
FROM quay.io/keycloak/keycloak:26.2.0 AS builder

# Adding custom providers
COPY themes/ /opt/keycloak/themes/
ADD --chown=keycloak:keycloak --chmod=644 tmp/javascript-providers.jar /opt/keycloak/providers/
# ... we have couple more

WORKDIR /opt/keycloak

RUN /opt/keycloak/bin/kc.sh build --verbose

# Using FROM quay.io/keycloak/keycloak:26.2.0 doesn't work too
FROM bellsoft/liberica-runtime-container:jdk-21-slim-musl
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENV KC_HTTP_ENABLED=true
ENV KC_PROXY_HEADERS=xforwarded

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--optimized"]
```

**Comment by shawkins** [comment]
> When I try to build the image on a Linux EC2 (our CI system) and deploy it to Kubernetes the issue starts to happen.

Does that pipeline invole docker save / load? 

What is shown in https://github.com/keycloak/keycloak/issues/38893#issuecomment-2798930620 seems to match https://github.com/moby/moby/issues/48447

Otherwise I've tried messing around with a few other docker constructs such as the SOURCE_DATE_EPOCH and still can't reproduce the behavior described here.

**Comment by shawkins** [comment]
> No. It's just a simple docker build -t ....

And the output image sha is the one that locally or in kubernetes displays the issue with timestamps?

Do you have access to that docker configuration?

**Comment by bahaa** [comment]
> > No. It's just a simple docker build -t ....
> 
> And the output image sha is the one that locally or in kubernetes displays the issue with timestamps?

We don't use reproducible builds. So file timestamps always change the sha of the image.

> 
> Do you have access to that docker configuration?

[Here](https://github.com/keycloak/keycloak/issues/38893#issuecomment-2806082239)

**Comment by shawkins** [comment]
> https://github.com/keycloak/keycloak/issues/38893#issuecomment-2806082239

That shows the versions, but I think we've already determined the behavior isn't version dependent. I'm looking foring arguments to dockerd or the daemon.json file.

**Comment by bahaa** [comment]
> > [#38893 (comment)](https://github.com/keycloak/keycloak/issues/38893#issuecomment-2806082239)
> 
> That shows the versions, but I think we've already determined the behavior isn't version dependent. I'm looking foring arguments to dockerd or the daemon.json file.

We didn't customize docker in anyway. Here is the content of `daemon.json` file:
```
{"hosts": ["tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"]}
```

**Comment by MarcusDunn** [comment]
here's my `docker info`
```
Client: Docker Engine - Community
 Version:    28.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.35.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 34
  Running: 2
  Paused: 0
  Stopped: 32
 Images: 34
 Server Version: 28.1.1
 Storage Driver: overlay2
  Backing Filesystem: zfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.11.0-21-generic
 Operating System: Ubuntu 24.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.27GiB
 Name: marcus-MS-7B17
 ID: 7c501770-d5ab-4933-91e8-aa2428f0238d
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

the only thing mildly weird is that I'm using ZFS. My drive is also encrypted, but I doubt docker can tell.

**Comment by shawkins** [comment]
Confirmed the issue with docker load / save: https://github.com/moby/moby/issues/48447 - but at least on my first attempt didn't see the same problem with push / pull.

From https://github.com/moby/moby/issues/17175 I could not reproduce either the COPY behavior, nor the commit.

There is also https://github.com/moby/moby/issues/40004 indicating an issue with RUN.

So it does look like at one point or another there have been problems with docker's handling of modification timestamps with load / save, push / pull, commit, and RUN / COPY - which isn't exactly confidence inspiring.

However since I can't reproduce much with either minikube docker instance or a freshly installed 28.1.1 Docker, it does seem like there could be version dependent or even more subtle behavior with caching that is coming into play. 

> We didn't customize docker in anyway. Here is the content of daemon.json file:

Thanks for checking. It's not very satisfying there isn't an obvious answer here.

If it seems like all situations involve truncated timestamps, we can also add to the list of possible resolutions - just change what we persist to be the truncated value.

**Comment by vmuzikar** [comment]
If it's essentially a docker issue, I'd argue not to fix that on our end. That said, trimming timestamps to seconds (if I understand the proposed fix) seems reasonable and would make it more robust.

**Comment by DimiF4W** [comment]
I have the same problem but with touch I still get the same error, this is my Dockerfile:


```
FROM quay.io/keycloak/keycloak:26.2 AS builder

ENV KC_DB=postgres

ADD --chown=keycloak:keycloak --chmod=644 /target/plugins.jar /opt/keycloak/providers/
RUN touch -m --date=@1743465600 /opt/keycloak/providers/*.

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:26.2
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

What is wrong with this workaround? Still see
`ERROR: A provider JAR was updated since the last build, please rebuild for this to be fully utilized.`

I never had problems before

**Comment by shawkins** [comment]
> What is wrong with this workaround? 

@DimiF4W you have a COPY occurring after the touch, which may be different that the other workarounds mentioned here.

You may need an additional touch after that copy or can you try copy --link?

**Comment by bahaa** [comment]
@DimiF4W I see a dot after the wild card here `RUN touch -m --date=@1743465600 /opt/keycloak/providers/*.`. I'm not sure, but you can try to remove that dot.

**Comment by DimiF4W** [comment]
> [@DimiF4W](https://github.com/DimiF4W) I see a dot after the wild card here `RUN touch -m --date=@1743465600 /opt/keycloak/providers/*.`. I'm not sure, but you can try to remove that dot.

Removing the dot did the trick :/ Thanks!

**Comment by shawkins** [comment]
> Removing the dot did the trick :/ Thanks!

Good catch @bahaa 

We've discussed this and #38801 offline and will start by documenting both as known issues with docker.

**Comment by shawkins** [comment]
Thank you for confirm the push / pull case. 

For those following this issue, would language like this in the docs be sufficiently helpful: https://github.com/keycloak/keycloak/pull/39162/files

**Comment by shawkins** [comment]
@dejwsz yes, there's that one and at least 2 others mentioned in https://github.com/keycloak/keycloak/issues/38893#issuecomment-2819282113

**Comment by dejwsz** [comment]
So, it looks like it was done on purpose in moby/buildkit - if it is by design not likely to be changed - then checking of provider jar timestamp is not a good idea in that case ? and the approach should be different ?

**Comment by shawkins** [comment]
> So, it looks like it was done on purpose in moby/buildkit - if it is by design not likely to be changed

It looks like the motiviation for that change was quite specific - compatibility with an old version of go - and may no longer be valid.

>  then checking of provider jar timestamp is not a good idea in that case ? and the approach should be different ?

Out of the options enumerated on https://github.com/keycloak/keycloak/issues/38893#issuecomment-2820992986 documenting this issue was best path forward in the short run. The docker bug(s) affect more than just keycloak, and it does seem like the community expects it to be addressed - eventually.

We will probably want to open a new discussion / issue to consider any other changes on the keycloak side.

**Comment by brutaldev** [comment]
We are still getting this with 26.2.4-0

The reason being that the build happens on one server and the provider files get copied to a mount which changes their timestamps. When Keycloak tries to start the timestamps will be different despite the provider files being exactly the same. We cannot "touch" the files at the mount point because it's in cloud storage without that functionality.

Is it possible to disable the flakey timestamp check?

**Comment by shawkins** [comment]
> Is it possible to disable the flakey timestamp check?

Please start a new issue. As you can see on this one we ultimately decided to document how to touch the files and relaxed the check to be tolerant to ms truncation.

**Comment by myousstools** [comment]
#

> For us this helped in our multi-stage Dockerfile:
> 
> 1. Copy everything like provider, themes with chown: `COPY --chown=keycloak:keycloak ...`
> 2. Touch the provider jar and fix its timestamp back in time before optimized build like:
> 
> ```
> RUN touch -m -t "$(date -u -d '1 hour ago' +%Y%m%d%H%M.%S)" /opt/keycloak/providers/my-test-spi-jar-with-dependencies.jar && /opt/keycloak/bin/kc.sh build
> ```
> 
> Chown is required to be able to modify the jar timestamp, otherwise you get permission denied error.

Working for me :

`
RUN find /opt/keycloak/providers/ -name "*.jar"  -exec touch -m -t "$(date -u -d "@$(( $(date +%s) - 3600 ))" +%Y%m%d%H%M.%S)" {} \;
`

**Comment by josteitv** [comment]
I ran into this issue while building an optimized Keycloak docker image, but the suggested [documented solution of setting the timestamp of the provider files to April 1th 2025](https://www.keycloak.org/server/containers#_known_issues_with_docker) does not work as intended if you are using [kaniko ](https://github.com/GoogleContainerTools/kaniko) to build the docker image.

To be able to build a image using kaniko that actually starts up, you have to use the kaniko option `--reproducible`, which sets all timestamps in the image to epoch, and then also use touch to set the provider files timestamp to epcoh:
`RUN touch -m --date=@0 /opt/keycloak/providers/*`

I'll leave this comment as a reference to others that may have problems building Keycloak in a build pipeline using kaniko.

**Comment by mfredenhagen** [comment]
This is still not solved for us. We are using the [Ironbank](https://p1.dso.mil/ironbank) process to repackage our custom Keycloak image, and are dependent on Ironbank's build process. The underlying tool is `buildah`, which modifies file timestamps in the layer AFTER the build has finished. No way for us to change that.
Therefore, we think that the chosen approach of recording file timestamps is wrong! It doesn't mean anything when deciding whether the optimisation was applied, as can be seen by the provided hacks for touching these files.
We therefore request that this be related to file hashes, and by this, it depends on the file contents.

**Comment by davinkevin** [comment]
And doing a `touch` at `runtime` to match the "expected" timestamp is incompatible with `readOnlyFileSystem` attribute. 

Please, offer a solution based on hash/digest, that would be better… especially when used with a tool like Buildah, from the same company 😇

**Comment by shawkins** [comment]
@mfredenhagen and @davinkevin please start a new disucussion or issue.

**Comment by davinkevin** [comment]
[Done ✅](https://github.com/keycloak/keycloak/issues/41268)

**Comment by bartlomiejduda** [comment]
This solution worked for me:

// buildah
buildah run $runtimecontainer -- find /opt/keycloak/providers -type f -exec touch -a -m --date=@1743465600 {} +

// docker
RUN find /opt/keycloak/providers -type f -exec touch -a -m --date=@1743465600 {} +
