### ISSUE TITLE
includeInAccessTokenResponse.label and includeInAccessTokenResponse.label.tooltip english messages are missing

### ISSUE THREAD

**Issue by cgeorgilakis** [keycloak/keycloak#9364]
### Describe the bug

![includeInAccessTokenLabel](https://user-images.githubusercontent.com/55974447/147754015-b82c8c7d-9351-4d0f-8db7-1c1f79a368a5.png)

As you can see from attached screenshot includeInAccessTokenResponse.label and includeInAccessTokenResponse.label.tooltip english messages are missing.

This bug exists also in previous versions.

### Version

16.1

**Comment by ssilvert** [comment]
Linked JIRA: https://issues.redhat.com/browse/KEYCLOAK-19329

**Comment by edewit** [comment]
@abstractj what about the help text?

**Comment by abstractj** [comment]
@edewit I'd suggest taking a look at the discussion inside https://github.com/keycloak/keycloak/pull/7371. The author clarified the purpose for this field.

**Comment by edewit** [comment]
fixed by #7773

**Comment by larsw** [comment]
![image](https://user-images.githubusercontent.com/63235/198380935-a10d3b87-614f-4067-8920-2a546e156e03.png)

Should be reopened - still a problem in the nightly docker image today.
