### ISSUE TITLE
Allow keycloak-js default export to be used as a constructor

### ISSUE THREAD

**Issue by RoiEXLab** [keycloak/keycloak#9848]
### Describe the bug

Imagine the following code:
```ts
import Keycloak from 'keycloak-js';

const keycloak = new Keycloak();
```

Using JavaScript (without TypeScript) this code works absolutely fine, but with TypeScript it doesn't "compile"

### Version

Latest

### Expected behavior

Due to the nature of the underlying plain JavaScript I would expect both notations with and without `new` keyword to work.

### Actual behavior

Using the `new` keyword doesn't work in TypeScript

**Comment by jonkoops** [comment]
Fixed in #9964

**Comment by damnedOperator** [comment]
Still have the error regarding missing constructor signatures. @jonkoops any suggestions on how to fix that? (Js Adapter version 17.0.1)

**Comment by jonkoops** [comment]
The changes to the type definitions have not been released yet, they will be released in a future version.

**Comment by damnedOperator** [comment]
Ok that's a bummer. Any workarounds?

**Comment by RoiEXLab** [comment]
@damnedOperator You can cast the type with typescript tooling to match your requirements. That's what I did for now. It looks a little bit ugly but works no problem

**Comment by jonkoops** [comment]
Yeah that would be the best approach for now. Unfortunately releases of Keycloak JS are tied to the release process of Keycloak itself so we cannot simply publish a new version of the JS adapter.
