### ISSUE TITLE
Upgrade to keycloak 15.1.1 Migration failed for change set META-INF/jpa-changelog-13.0.0.xml::default-roles::keycloak

### ISSUE THREAD

**Issue by shubhamarora97** [keycloak/keycloak#9886]
### Describe the bug

Hello,

I'm trying to upgrade from keycloak 11.0.3 to keycloak 15.1.1

On start I have theses error, any ideas ?

I'm starting with /opt/keycloak/bin/standalone.sh -Dkeycloak.profile.feature.scripts=enabled

21:05:26,951 INFO  [org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory] (ServerService Thread Pool -- 63) Database info: {databaseUrl=jdbc:mysql://localhost:3306/keycloak?characterEncoding=UTF-8&serverTimezone=UTC, databaseUser=keycloak@localhost, databaseProduct=MySQL 5.5.5-10.3.32-MariaDB-0ubuntu0.20.04.1, databaseDriver=MySQL Connector/J mysql-connector-java-8.0.13 (Revision: 66459e9d39c8fd09767992bc592acd2053279be6)}
21:05:29,224 INFO  [org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider] (ServerService Thread Pool -- 63) Updating database. Using changelog META-INF/jpa-changelog-master.xml
21:05:29,393 ERROR [org.keycloak.connections.jpa.updater.liquibase.conn.DefaultLiquibaseConnectionProvider] (ServerService Thread Pool -- 63) Change Set META-INF/jpa-changelog-13.0.0.xml::default-roles::keycloak failed.  Error: Duplicate column name 'DEFAULT_ROLE' [Failed SQL: ALTER TABLE keycloak.REALM ADD DEFAULT_ROLE VARCHAR(255) NULL]
21:05:29,394 ERROR [org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider] (ServerService Thread Pool -- 63) Error has occurred while updating the database: liquibase.exception.MigrationFailedException: Migration failed for change set META-INF/jpa-changelog-13.0.0.xml::default-roles::keycloak:
     Reason: liquibase.exception.DatabaseException: Duplicate column name 'DEFAULT_ROLE' [Failed SQL: ALTER TABLE keycloak.REALM ADD DEFAULT_ROLE VARCHAR(255) NULL]
    at liquibase.changelog.ChangeSet.execute(ChangeSet.java:619)
    at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
    at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79)
    at liquibase.Liquibase.update(Liquibase.java:214)
    at liquibase.Liquibase.update(Liquibase.java:192)
    at liquibase.Liquibase.update(Liquibase.java:188)
    at org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider.updateChangeSet(LiquibaseJpaUpdaterProvider.java:184)
    at org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider.update(LiquibaseJpaUpdaterProvider.java:103)
    at org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider.update(LiquibaseJpaUpdaterProvider.java:82)
    at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory$2.run(DefaultJpaConnectionProviderFactory.java:383)
    at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:239)
    at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.update(DefaultJpaConnectionProviderFactory.java:376)
    at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.migration(DefaultJpaConnectionProviderFactory.java:364)
    at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.lambda$lazyInit$0(DefaultJpaConnectionProviderFactory.java:211)
    at org.keycloak.models.utils.KeycloakModelUtils.suspendJtaTransaction(KeycloakModelUtils.java:753)
    at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.lazyInit(DefaultJpaConnectionProviderFactory.java:162)
    at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.create(DefaultJpaConnectionProviderFactory.java:87)
    at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.create(DefaultJpaConnectionProviderFactory.java:65)
    at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:316)
    at org.keycloak.models.jpa.JpaRealmProviderFactory.create(JpaRealmProviderFactory.java:64)
    at org.keycloak.models.jpa.JpaRealmProviderFactory.create(JpaRealmProviderFactory.java:40)
    at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:316)
    at org.keycloak.services.DefaultKeycloakSession.realmLocalStorage(DefaultKeycloakSession.java:228)
    at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealmDelegate(RealmCacheSession.java:149)
    at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealm(RealmCacheSession.java:422)
    at org.keycloak.services.managers.ApplianceBootstrap.isNewInstall(ApplianceBootstrap.java:46)
    at org.keycloak.services.resources.KeycloakApplication$3.run(KeycloakApplication.java:195)
    at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:239)
    at org.keycloak.services.resources.KeycloakApplication.bootstrap(KeycloakApplication.java:172)
    at org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:136)
    at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:239)
    at org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:128)
    at org.keycloak.provider.wildfly.WildflyPlatform.onStartup(WildflyPlatform.java:36)
    at org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:114)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:152)
    at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2835)
    at org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:376)
    at org.jboss.resteasy.spi.ResteasyDeployment.startInternal(ResteasyDeployment.java:288)
    at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:98)
    at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:140)
    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:42)
    at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
    at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
    at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
    at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:305)
    at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:145)
    at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:588)
    at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:559)
    at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
    at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
    at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
    at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:601)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:97)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
    at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
    at java.lang.Thread.run(Thread.java:748)
    at org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: liquibase.exception.DatabaseException: Duplicate column name 'DEFAULT_ROLE' [Failed SQL: ALTER TABLE keycloak.REALM ADD DEFAULT_ROLE VARCHAR(255) NULL]
    at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:309)
    at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
    at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:113)
    at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1277)
    at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1259)
    at liquibase.changelog.ChangeSet.execute(ChangeSet.java:582)
    ... 69 more
Caused by: java.sql.SQLSyntaxErrorException: Duplicate column name 'DEFAULT_ROLE'
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
    at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:782)
    at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:666)
    at org.jboss.jca.adapters.jdbc.WrappedStatement.execute(WrappedStatement.java:198)
    at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:307)
    ... 74 more

21:05:29,405 FATAL [org.keycloak.services] (ServerService Thread Pool -- 63) Error during startup: java.lang.RuntimeException: Failed to update database
    at org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider.update(LiquibaseJpaUpdaterProvider.java:118)
    at org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider.update(LiquibaseJpaUpdaterProvider.java:82)
    at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory$2.run(DefaultJpaConnectionProviderFactory.java:383)
    at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:239)
    at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.update(DefaultJpaConnectionProviderFactory.java:376)
    at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.migration(DefaultJpaConnectionProviderFactory.java:364)
    at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.lambda$lazyInit$0(DefaultJpaConnectionProviderFactory.java:211)
    at org.keycloak.models.utils.KeycloakModelUtils.suspendJtaTransaction(KeycloakModelUtils.java:753)
    at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.lazyInit(DefaultJpaConnectionProviderFactory.java:162)
    at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.create(DefaultJpaConnectionProviderFactory.java:87)
    at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.create(DefaultJpaConnectionProviderFactory.java:65)
    at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:316)
    at org.keycloak.models.jpa.JpaRealmProviderFactory.create(JpaRealmProviderFactory.java:64)
    at org.keycloak.models.jpa.JpaRealmProviderFactory.create(JpaRealmProviderFactory.java:40)
    at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:316)
    at org.keycloak.services.DefaultKeycloakSession.realmLocalStorage(DefaultKeycloakSession.java:228)
    at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealmDelegate(RealmCacheSession.java:149)
    at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealm(RealmCacheSession.java:422)
    at org.keycloak.services.managers.ApplianceBootstrap.isNewInstall(ApplianceBootstrap.java:46)
    at org.keycloak.services.resources.KeycloakApplication$3.run(KeycloakApplication.java:195)
    at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:239)
    at org.keycloak.services.resources.KeycloakApplication.bootstrap(KeycloakApplication.java:172)
    at org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:136)
    at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:239)
    at org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:128)
    at org.keycloak.provider.wildfly.WildflyPlatform.onStartup(WildflyPlatform.java:36)
    at org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:114)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:152)
    at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2835)
    at org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:376)
    at org.jboss.resteasy.spi.ResteasyDeployment.startInternal(ResteasyDeployment.java:288)
    at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:98)
    at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:140)
    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:42)
    at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
    at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
    at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
    at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:305)
    at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:145)
    at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:588)
    at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:559)
    at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
    at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
    at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
    at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:601)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:97)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
    at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
    at java.lang.Thread.run(Thread.java:748)
    at org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set META-INF/jpa-changelog-13.0.0.xml::default-roles::keycloak:
     Reason: liquibase.exception.DatabaseException: Duplicate column name 'DEFAULT_ROLE' [Failed SQL: ALTER TABLE keycloak.REALM ADD DEFAULT_ROLE VARCHAR(255) NULL]
    at liquibase.changelog.ChangeSet.execute(ChangeSet.java:619)
    at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
    at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79)
    at liquibase.Liquibase.update(Liquibase.java:214)
    at liquibase.Liquibase.update(Liquibase.java:192)
    at liquibase.Liquibase.update(Liquibase.java:188)
    at org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider.updateChangeSet(LiquibaseJpaUpdaterProvider.java:184)
    at org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider.update(LiquibaseJpaUpdaterProvider.java:103)
    ... 62 more
Caused by: liquibase.exception.DatabaseException: Duplicate column name 'DEFAULT_ROLE' [Failed SQL: ALTER TABLE keycloak.REALM ADD DEFAULT_ROLE VARCHAR(255) NULL]
    at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:309)
    at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
    at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:113)
    at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1277)
    at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1259)
    at liquibase.changelog.ChangeSet.execute(ChangeSet.java:582)
    ... 69 more
Caused by: java.sql.SQLSyntaxErrorException: Duplicate column name 'DEFAULT_ROLE'
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
    at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:782)
    at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:666)
    at org.jboss.jca.adapters.jdbc.WrappedStatement.execute(WrappedStatement.java:198)
    at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:307)
    ... 74 more

### Version

15.1.1

### Actual behavior

Keycloak should be upgraded without any issues from 11.0.3 to 15.1.1

**Comment by shubhamarora97** [comment]
Does anyone have a workaround or solution to perform the upgrade ?

**Comment by shubhamarora97** [comment]
There was an issue in keycloak 15.1.1 with database schema script changes and was fixed in the next release(16.0.0).
https://github.com/keycloak/keycloak/issues/9138
https://github.com/keycloak/keycloak/pull/9140

I made the source code changes with the fix and built it with Java 8. Liquibase database upgrade issue was resolved.
@vramik  This regression was present in 15.1.0 and 15.1.1 and can also be fixed in those binaries as well so that there is no issue with database upgrade issue.

**Comment by vramik** [comment]
Thank you @shubhamarora97!

**Comment by squaricdot** [comment]
i could not get keycloak 15.1.1 working with any infinispan higher than 12.1.11, I could not get keycloak 16 working with infinispan at all afair (spend whole week, ending up with above versions, which do meet the security requirements, also for infinispan for log4j ) 

and i can't update a running instance of 12.0.4, to 13.0.0 , nor 13.0.1, 14.0.0, 15.0.1, 15.1.1

with 15.1.1 i also get this error.

can try 16 but then there won't be infinispan.

**Comment by yogesh-pal** [comment]
Can't DROP COLUMN `DEFAULT_ROLE`; check that it exists
i'm getting this.

**Comment by fzyzcjy** [comment]
I see this problem in keycloak 22...

**Comment by okhimka** [comment]
Have this issue too in keycloak 22

**Comment by avijitmitra88** [comment]
I can too confirm that I have this issue in keycloak 22.0.1

**Comment by SebastianMelinat** [comment]
I got this error while trying to upgrade from version 11 to 22 (yes I know...).

This worked for me:

1. Upgrade from 11 to 13
2. Upgrade from 13 to 22

**Comment by shkmaaz11** [comment]
> I got this error while trying to upgrade from version 11 to 22 (yes I know...).
> 
> This worked for me:
> 
> 1. Upgrade from 11 to 13
> 2. Upgrade from 13 to 22

Hey, I'm trying to do the same. From 11 to 22. 
What exact steps did you follow?

**Comment by SebastianMelinat** [comment]
> > I got this error while trying to upgrade from version 11 to 22 (yes I know...).
> > This worked for me:
> > 
> > 1. Upgrade from 11 to 13
> > 2. Upgrade from 13 to 22
> 
> Hey, I'm trying to do the same. From 11 to 22. What exact steps did you follow?

I simply deployed version 13 and waited for it to have completed the start up, then deployed version 22

**Comment by totallyben** [comment]
> I got this error while trying to upgrade from version 11 to 22 (yes I know...).
> 
> This worked for me:
> 
> 1. Upgrade from 11 to 13
> 2. Upgrade from 13 to 22

Thanks @SebastianMelinat this worked for me.

I did have to manually drop the REALM_LOCALIZATIONS table in order to complete the upgrade from 11 to 13 but otherwise was a straight upgrade

**Comment by tariyal89** [comment]
> oo confirm that I have this issue in keycloak 22.0.1

How did you fix this on 22?

**Comment by tariyal89** [comment]
> > I got this error while trying to upgrade from version 11 to 22 (yes I know...).
> > This worked for me:
> > 
> > 1. Upgrade from 11 to 13
> > 2. Upgrade from 13 to 22
> 
> Hey, I'm trying to do the same. From 11 to 22. What exact steps did you follow?

Did you find any solution?

**Comment by svkoblov** [comment]
Faced the same issue while migrating Keycloak DB from earlier version to the latest 22.0.3
My workaround was to upgrade DB for Keycloak v21.0.1 first? then apply v22.0.3 update finally.
So it seems to be related with incorrect DB migration scipt violating table constraint when creating default realm roles.
As it was successfull for me to upgrade DB on Keycloak v21 from earlier version (without default roles) and it failed only during ugrade attempt on Keycloak v22 - I suppose there's something wrong with this part in latest Keycloak version now

**Comment by lrozenblyum** [comment]
@svkoblov @tariyal89 @totallyben @shkmaaz11 @avijitmitra88 @okhimka 
The bug https://github.com/keycloak/keycloak/issues/23220 was fixed, let's wait for the 22.0.5 release.

**Comment by SebastianMelinat** [comment]
I'm still getting this error with 22.0.5. Did anybody else try?

**Comment by miguelingitj** [comment]
> I got this error while trying to upgrade from version 11 to 22 (yes I know...).
> 
> This worked for me:
> 
> 1. Upgrade from 11 to 13
> 2. Upgrade from 13 to 22

This also work for me!
